import type { PageManifestEntry } from "../../lib/page-manifest";
import { AdminShell } from "../../components/shells/Shells";
import { entityFields, entityForPath, type EntityName } from "../../content/entities";

function AdminHead({ screen, description }: { screen: PageManifestEntry; description: string }) {
  return <header className="workspace-page-head"><p className="kicker">ADMIN · {screen.screenId}</p><h1>{screen.title}</h1><p>{description}</p></header>;
}

function DataIndex({ screen }: { screen: PageManifestEntry }) {
  return <><AdminHead screen={screen} description="Canonical object types and their administrative tasks." /><div className="entity-grid">{Object.entries(entityFields).map(([entity, fields]) => <a className="card" href={`/admin/data/${entity.toLowerCase()}`} key={entity}><h2>{entity}</h2><p>{fields.length} current fields</p><span>Open records →</span></a>)}</div></>;
}

function EntityTable({ screen, entity }: { screen: PageManifestEntry; entity: EntityName }) {
  const fields = entityFields[entity];
  return <><AdminHead screen={screen} description={`${entity} records using the current canonical field contract.`} /><div className="toolbar"><input className="input" aria-label={`Search ${entity}`} placeholder={`Search ${entity}`} /><select className="select compact" aria-label="Status"><option>All statuses</option></select><a className="button" href={`${screen.path?.split("?")[0]}/import`}>Import</a><a className="button button--gold" href={`${screen.path?.split("?")[0]}/new`}>New {entity}</a></div><section className="card table-scroll"><table className="data-table"><thead><tr>{fields.slice(0, 6).map((field) => <th key={field}>{field}</th>)}<th>Actions</th></tr></thead><tbody><tr>{fields.slice(0, 6).map((field, index) => <td key={field}>{index === 0 ? `${entity.toUpperCase()}-001` : "—"}</td>)}<td><a href={`${screen.path?.split("?")[0]}/sample-record`}>Edit</a></td></tr></tbody></table></section></>;
}

function EntityEditor({ screen, entity }: { screen: PageManifestEntry; entity: EntityName }) {
  const fields = entityFields[entity];
  return <><AdminHead screen={screen} description={`${entity} editor with entity-specific fields and controlled relationships.`} /><div className="split"><form className="card form-grid">{fields.map((field) => <label className={`field ${["description", "summary", "notes", "baseContent"].includes(field) ? "span-2" : ""}`} key={field}>{field}{["description", "summary", "notes", "baseContent"].includes(field) ? <textarea className="textarea" /> : <input className="input" />}</label>)}<div className="action-row span-2"><button className="button button--gold">Save changes</button><button className="button">Cancel</button></div></form><aside className="card"><h2>Record relationships</h2><p>Linked records use exact IDs and controlled lookups.</p><div className="schema-list">{fields.map((field) => <span key={field}>{field}</span>)}</div><h3>Change summary</h3><p>Fields changed in this editor update the selected canonical record only.</p></aside></div></>;
}

function EntityImport({ screen, entity }: { screen: PageManifestEntry; entity: EntityName }) {
  const fields = entityFields[entity];
  return <><AdminHead screen={screen} description={`Validate, preview, and apply ${entity} rows without writing during preview.`} /><div className="grid-3"><section className="card"><h2>1 · Source</h2><p>Upload JSON, YAML or CSV data.</p><input className="input" type="file" accept=".json,.yaml,.yml,.csv" /><button className="button">Paste data</button></section><section className="card"><h2>2 · Field mapping</h2><div className="schema-list">{fields.map((field) => <span key={field}>{field} → {field}</span>)}</div><p>Unknown fields stay blocked until explicitly mapped.</p></section><section className="card"><h2>3 · Validation</h2><p><span className="tag tag--good">2 valid rows</span></p><p>Required IDs present</p><p>Controlled values recognized</p><p>Referenced IDs resolve or are reported before apply</p><button className="button button--good">Preview import</button></section></div><section className="card import-preview"><div className="action-row"><h2>Preview</h2><span className="tag">No writes yet</span></div><div className="table-scroll"><table className="data-table"><thead><tr>{fields.slice(0, 6).map((field) => <th key={field}>{field}</th>)}</tr></thead><tbody><tr>{fields.slice(0, 6).map((field, index) => <td key={field}>{index === 0 ? `${entity.toUpperCase()}-001` : "—"}</td>)}</tr></tbody></table></div><div className="action-row"><button className="button button--gold">Apply 2 rows</button><button className="button">Download validation report</button></div></section></>;
}

function CreateAntagonist({ screen }: { screen: PageManifestEntry }) {
  const fields = entityFields.Antagonist;
  return <><AdminHead screen={screen} description="Create an Antagonist with direct current relationships." /><div className="split"><form className="card form-grid">{fields.map((field) => <label className="field" key={field}>{field}<input className="input" /></label>)}<button className="button button--gold span-2">Create Antagonist</button></form><aside className="card"><h2>Current constraints</h2><p>Each Antagonist links directly to one Architect, one LegendaryReward and one puzzle blueprint.</p><p>Constellation relationships are optional before/after links.</p></aside></div></>;
}

function CreateCharacter({ screen }: { screen: PageManifestEntry }) {
  return <><AdminHead screen={screen} description="Create a Character through the current Character → Breed → Species/Culture relationship." /><div className="split"><form className="card form-grid"><label className="field">characterId<input className="input" /></label><label className="field">displayName<input className="input" /></label><label className="field span-2">breedId<select className="select"><option>Select Breed</option></select></label><button className="button button--gold span-2">Create Character</button></form><aside className="card"><h2>Resolved through Breed</h2><p>Species and optional Culture are displayed from the selected Breed. They are not separate Character fields.</p></aside></div></>;
}

function PuzzlePage({ screen }: { screen: PageManifestEntry }) {
  if (["PZ002", "PZ003"].includes(screen.screenId)) return <><AdminHead screen={screen} description={screen.screenId === "PZ003" ? "Run a blueprint without changing canonical data." : "Edit the current puzzle blueprint contract."} /><div className="split"><form className="card form-grid"><label className="field">puzzleBlueprintId<input className="input" defaultValue="PB-001" /></label><label className="field">family<input className="input" /></label><label className="field">difficultyTier<input className="input" type="number" min="1" max="5" /></label><label className="field">generatorVersion<input className="input" type="number" min="1" /></label><label className="field span-2">hint1<textarea className="textarea" /></label><label className="field span-2">hint2<textarea className="textarea" /></label><button className="button button--gold span-2">{screen.screenId === "PZ003" ? "Run test" : "Save blueprint"}</button></form><aside className="card"><h2>{screen.screenId === "PZ003" ? "Validation" : "Preview"}</h2><p>Blueprint test output and validation appear here.</p></aside></div></>;
  if (screen.screenId === "ADM029") return <><AdminHead screen={screen} description="Shared interaction components used by puzzle blueprints." /><div className="grid-3">{[["Cipher Grid", "Letter/number grid with keyboard and touch controls."], ["Sequence Rack", "Ordered slots with drag, keyboard pick-and-place and validation."], ["Spatial Board", "Grid-based placement with coordinates and alternate text description."], ["Audio Phrase", "Playable tonal phrase paired with non-audio notation."], ["Construction Tray", "Parts inventory with snap targets and reversible placement."], ["Source Reader", "Document excerpt with citations and selectable claims."]].map(([name, body]) => <article className="card" key={name}><h2>{name}</h2><p>{body}</p><span className="tag">Reusable</span></article>)}</div></>;
  if (screen.screenId === "ADM030") return <><AdminHead screen={screen} description="Test puzzle blueprints and review validation results." /><div className="split"><section className="card"><h2>Test configuration</h2><label className="field">Blueprint<select className="select"><option>PB-001</option></select></label><label className="field">Difficulty tier<input className="input" type="number" min="1" max="5" /></label><button className="button button--gold">Run validation</button></section><aside className="card"><h2>Results</h2><p>No test has run in this session.</p></aside></div></>;
  return <><AdminHead screen={screen} description="Create, inspect and test puzzle blueprints." /><div className="toolbar"><input className="input" placeholder="Search blueprints" /><a className="button" href="/admin/puzzles/components">Reusable components</a><a className="button" href="/admin/puzzles/test-lab">Test lab</a><button className="button button--gold">New blueprint</button></div><EntityTable screen={{...screen, title: "Puzzle Blueprints"}} entity="CapabilityDefinition" /></>;
}

function AtlasPage({ screen }: { screen: PageManifestEntry }) {
  const isPoi = ["AT002", "AT003", "ADM032", "ATLAS_POI_2D", "ATLAS_POI_3D"].includes(screen.screenId);
  const is3d = ["AT003", "ATLAS_POI_3D"].includes(screen.screenId);
  if (screen.screenId === "AT004_FOUND_CITY") return <><AdminHead screen={screen} description="Found a city at SITE-0081 without selecting a world." /><div className="split"><form className="card form-grid"><label className="field">siteId<input className="input" value="SITE-0081" readOnly /></label><label className="field">settlement name<input className="input" /></label><label className="field">settlement size<select className="select"><option>City</option></select></label><label className="field">approved arrival<input className="input" value="90%" readOnly /></label><button className="button button--gold span-2">Found city</button></form><aside className="card"><h2>Population arrival</h2><p>Apply the approved 90% arrival to the selected Site population when the settlement is founded.</p><p className="notice notice--warn">Rounding remains owner-decision-required and is not guessed here.</p></aside></div></>;
  if (screen.screenId === "AT005_SETTLEMENT_DETAIL") return <><AdminHead screen={screen} description="Migrate population into SET-0001 while preserving exact Breed totals." /><div className="split"><section className="card"><h2>Source settlement</h2><label className="field">Settlement<select className="select"><option>SET-0002</option></select></label><label className="field">Population to migrate<input className="input" type="number" min="0" /></label><button className="button">Preview migration</button></section><aside className="card"><h2>Conservation check</h2><p>Each Breed population is conserved exactly between source and destination.</p><p>No allocation is applied unless sufficient source population exists.</p><button className="button button--gold">Apply migration</button></aside></div></>;
  if (isPoi) return <><AdminHead screen={screen} description="Browse Points of Interest using an explicitly selected 2D map, 3D globe, or list view." /><div className="tabs"><a className={!is3d ? "active" : ""} href="/admin/atlas/pois?state=ATLAS_POI_2D">2D Map</a><a className={is3d ? "active" : ""} href="/admin/atlas/pois?state=ATLAS_POI_3D">3D Globe</a><button>List</button></div><div className="atlas-layout"><section className={is3d ? "globe" : "map"}><img src={is3d ? "/assets/globe.png" : "/assets/world_map.png"} alt={is3d ? "3D globe view" : "2D world map"} />{!is3d && <span className="map-pin" />}</section><aside className="card"><h2>Selected Point of Interest</h2><p><strong>POI-0042 · Worldroot</strong></p><p>Kind: WORLD_TREE</p><p>Region: R13</p><p>Longitude: 14.255</p><p>Latitude: 1.721</p><button className="button button--gold">Open record</button></aside></div></>;
  if (["AT004", "ADM033"].includes(screen.screenId)) return <><AdminHead screen={screen} description="Sites and their settlement state." /><EntityTable screen={screen} entity="Site" /></>;
  if (["AT005", "ADM034"].includes(screen.screenId)) return <><AdminHead screen={screen} description="Settlements and population migration tasks." /><EntityTable screen={screen} entity="Settlement" /></>;
  return <><AdminHead screen={screen} description="Manage Points of Interest, Sites and Settlements." /><div className="grid-3"><a className="card" href="/admin/atlas/pois"><h2>Points of Interest</h2><p>2D map, 3D globe and list views.</p></a><a className="card" href="/admin/atlas/sites"><h2>Sites</h2><p>Candidate sites and founding tasks.</p></a><a className="card" href="/admin/atlas/settlements"><h2>Settlements</h2><p>Settlement records and migrations.</p></a></div></>;
}

function CampaignPage({ screen }: { screen: PageManifestEntry }) {
  const planner = screen.path?.includes("planner");
  if (!planner) return <><AdminHead screen={screen} description="Manage the three current campaign spans and their 18-book planners." /><div className="grid-3">{["Concord", "Ruin", "Schism"].map((world) => <a className="card" href={`/admin/campaign/planner?state=CAMPAIGN_${world.toUpperCase()}`} key={world}><h2>{world}</h2><p>Books 1–18</p><span>Open planner →</span></a>)}</div></>;
  const world = screen.screenId.includes("RUIN") ? "Ruin" : screen.screenId.includes("SCHISM") ? "Schism" : "Concord";
  return <><AdminHead screen={{...screen, title: `Main 18-Book Planner — ${world}`}} description={`${world} campaign assignments with direct Witness, Architect, Reward and TimelineEvent relationships.`} /><div className="toolbar"><button className="button">{world}</button><button className="button">Books 1–18</button><button className="button">All linked types</button><span className="grow" /><button className="button">Undo</button><button className="button">Redo</button></div>{screen.screenId === "CAM004" && <p className="notice notice--bad">Invalid Architect drop: the selected relationship is not accepted.</p>}<section className="card table-scroll"><table className="data-table campaign-table"><thead><tr>{["Book", "Pillar", "Lesson", "IN_TRANSIT", "EXODUS", "Transition", "DEJA_VU", "Companion", "ATROCITY", "Witness", "Architect", "Reward", "Interludes"].map((name) => <th key={name}>{name}</th>)}</tr></thead><tbody>{Array.from({length: 18}, (_, i) => <tr key={i}><td>{i + 1}</td><td>{i % 9 === 0 ? `PIL-${String(i / 9 + 1).padStart(2, "0")}` : "—"}</td><td>{i % 6 === 0 ? `LES-${String(i / 6 + 1).padStart(2, "0")}` : "—"}</td><td>{i % 6 === 0 ? `TE-IT-${i / 6 + 1}` : "—"}</td><td>{i % 3 === 0 ? `TE-EX-${i / 3 + 1}` : "—"}</td><td>{i % 2 ? "—" : `TR-${String(i + 1).padStart(2, "0")}`}</td><td>{i % 2 ? "—" : `INT-DV-${String(i + 1).padStart(2, "0")}`}</td><td>{i % 2 ? "—" : `COMP-${String(i + 1).padStart(2, "0")}`}</td><td>TE-A-{String(i + 1).padStart(2, "0")}</td><td>WIT-{String(i + 1).padStart(2, "0")}</td><td>ARCH-{String(i + 1).padStart(2, "0")}</td><td>LR-{String(i + 1).padStart(2, "0")}</td><td>{i % 3 === 2 ? "WWII · MYTH" : "SCIENCE"}</td></tr>)}</tbody></table></section><p className="notice">Linked groups: Witness ↔ Architect ↔ LegendaryReward ↔ ATROCITY TimelineEvent ↔ book interludes · Companion ↔ Transition ↔ DEJA_VU · Lesson ↔ IN_TRANSIT ↔ two EXODUS TimelineEvents.</p></>;
}

function CityPage({ screen }: { screen: PageManifestEntry }) {
  const descriptions: Record<string, string> = { CITY01: "Cities and their district plans.", CITY02: "Parcels and street graph for the selected city.", CITY03: "Buildings and exterior composition.", CITY04: "Interior spaces and connections.", CITY05: "Preview the city with district overlays.", ADM037: "Build city structure from streets through interiors." };
  return <><AdminHead screen={screen} description={descriptions[screen.screenId] ?? "City Builder task."} />{screen.screenId === "CITY05" ? <div className="atlas-layout"><section className="map"><img src="/assets/world_map.png" alt="City district overlay preview" /></section><aside className="card"><h2>District overlays</h2>{["Streets", "Parcels", "Buildings", "Interiors"].map((name) => <label key={name}><input type="checkbox" defaultChecked /> {name}</label>)}</aside></div> : <div className="split"><section className="card"><h2>{screen.title}</h2><div className="city-canvas">{screen.screenId === "CITY04" ? "Interior graph" : screen.screenId === "CITY03" ? "Building exteriors" : screen.screenId === "CITY02" ? "Parcel and street graph" : "City records"}</div></section><aside className="card"><h2>Selection</h2><label className="field">Name<input className="input" /></label><label className="field">Type<select className="select"><option>Select</option></select></label><button className="button button--gold">Save</button></aside></div>}</>;
}

function GeneralAdmin({ screen }: { screen: PageManifestEntry }) {
  if (screen.screenId === "ADM001") return <><AdminHead screen={screen} description="Administrative overview and current work queues." /><div className="grid-3">{[["Access approvals", "0"], ["Store orders", "0"], ["Data validations", "0"], ["Release tasks", "0"], ["Prompt work", "0"], ["Operations alerts", "0"]].map(([name, count]) => <article className="card" key={name}><h2>{name}</h2><p className="stat">{count}</p></article>)}</div></>;
  const cardsByScreen: Record<string, readonly string[]> = {
    ADM002: ["Accounts", "Search accounts and inspect access."], ADM003: ["Roles", "Assign and review administrative roles."], ADM004: ["Approval queue", "Review invitation and access requests."], ADM005: ["Account detail", "Inspect account access and roles."], ADM006: ["Invitation codes", "Create, inspect and revoke invitation codes."],
    ADM007: ["Donation perks", "Review donation-linked member time."], ADM008: ["Perk detail", "Edit a donation perk boundary."], ADM010: ["Store management", "Manage the exact approved catalog."], ADM011: ["Store categories", "Posters, mugs and hoodies."], ADM012: ["Store items", "One mug, one hoodie and one poster."], ADM013: ["Store item editor", "Artwork, variant, price and Printful fulfillment."],
    ADM014: ["Order management", "Merchandise, subscriptions and donations remain separate."], ADM015: ["Merchandise orders", "Stripe payment and Printful fulfillment states."], ADM016: ["Subscriptions", "Subscription payment and status."], ADM017: ["Donations", "Donation payments and member time."], ADM018: ["Order detail", "Administrative order actions and audit."],
    ADM020: ["Bulk operations", "Validate and preview before apply."], ADM021: ["External API", "Enabled key and scoped access."], ADM022: ["Recent activity", "Bulk-operation audit history."], ADM031: ["Audio assets", "Upload and manage audio assets."], ADM032: ["Video assets", "Upload and manage video assets."], ADM033: ["Prompt manager", "Review prompt records."], ADM034: ["Outstanding prompts", "Only prompt work still outstanding."],
    OPS001: ["Operations", "Service and worker health."], OPS002: ["Release management", "Prepare and verify releases without deployment."],
  };
  const [title, body] = cardsByScreen[screen.screenId] ?? [screen.title, "Reviewed administrative task."];
  return <><AdminHead screen={screen} description={body} /><div className="split"><section className="card"><h2>{title}</h2><div className="toolbar"><input className="input" placeholder="Search" /><button className="button">Filter</button><button className="button button--gold">Create</button></div><table className="data-table"><thead><tr><th>ID</th><th>Name</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr><td>—</td><td>No records loaded</td><td>—</td><td>—</td></tr></tbody></table></section><aside className="card"><h2>Task boundary</h2><p>{body}</p></aside></div></>;
}

export function AdminPage({ screen }: { screen: PageManifestEntry }) {
  const entity = entityForPath(screen.path);
  let page;
  if (screen.screenId === "DATA000") page = <DataIndex screen={screen} />;
  else if (screen.screenId === "DATA_ANTAGONIST_NEW") page = <CreateAntagonist screen={screen} />;
  else if (screen.screenId === "DATA_CHARACTER_NEW") page = <CreateCharacter screen={screen} />;
  else if (screen.screenId.endsWith("_IMPORT") && entity) page = <EntityImport screen={screen} entity={entity} />;
  else if (screen.screenId.endsWith("_EDIT") && entity) page = <EntityEditor screen={screen} entity={entity} />;
  else if ((screen.screenId.startsWith("DATA") || screen.screenId === "DATA_ANTAGONIST_TABLE") && entity) page = <EntityTable screen={screen} entity={entity} />;
  else if (screen.path?.startsWith("/admin/puzzles")) page = <PuzzlePage screen={screen} />;
  else if (screen.path?.startsWith("/admin/atlas")) page = <AtlasPage screen={screen} />;
  else if (screen.path?.startsWith("/admin/campaign")) page = <CampaignPage screen={screen} />;
  else if (screen.path?.startsWith("/admin/cities") || screen.path === "/admin/city-builder") page = <CityPage screen={screen} />;
  else page = <GeneralAdmin screen={screen} />;
  return <AdminShell>{page}</AdminShell>;
}
