import { useQuery } from "@tanstack/react-query";
import { useState } from "react";

import type { ReleaseNotes } from "../../domain/release-notes";
import type { PageManifestEntry } from "../../lib/page-manifest";

function ReleaseManager() {
  const releases = useQuery({ queryKey: ["admin", "releases"], queryFn: async () => { const response = await fetch("/api/admin/releases"); if (!response.ok) throw new Error("Release records could not be loaded."); return response.json() as Promise<{ releases: ReleaseNotes[] }>; } });
  return <div className="stack"><section className="card"><h2>Canonical release authority</h2><p>Release drafts are owner-reviewed Markdown in the production repository. Runtime forms cannot create or publish competing release records.</p></section><section className="card"><h2>Release records</h2>{releases.isPending ? <p>Loading releases…</p> : releases.isError ? <p className="notice notice--bad">{releases.error.message}</p> : releases.data.releases.length === 0 ? <p>No canonical release records.</p> : <div className="table-scroll"><table className="simple-table"><thead><tr><th>Version</th><th>Status</th><th>Title</th><th>Summary</th><th>Date</th><th>Items</th><th>Publication</th><th>Deployment</th></tr></thead><tbody>{releases.data.releases.map((release) => <tr key={release.version}><td>{release.version}</td><td>{release.status}</td><td>{release.title}</td><td>{release.summary}</td><td>{release.releaseDate ?? "Not assigned"}</td><td>{release.items.length}</td><td><button className="button" disabled>Owner-reviewed repository change required</button></td><td><button className="button" disabled>Requires explicit authorization</button></td></tr>)}</tbody></table></div>}<p className="notice">Generated drafts never publish notes. Publication, tags, GitHub Releases, migrations, and application deployment remain separate authorized operations.</p></section></div>;
}

function DocumentBuilder() {
  const [selected, setSelected] = useState("");
  const [content, setContent] = useState("");
  const [message, setMessage] = useState("");
  const documents = useQuery({ queryKey: ["admin", "documents"], queryFn: async () => { const response = await fetch("/api/admin/documents"); if (!response.ok) throw new Error("Document buckets could not be loaded."); return response.json() as Promise<{ buckets: Array<{ documentBucketId: string; name: string; sourcePoints: Array<{ documentSourcePointId: string; ordinal: number; content: string; sourceLabel: string }>; amendments: Array<{ documentAmendmentId: string; ordinal: number; content: string }>; drafts: Array<{ documentDraftId: string; version: number; status: string }> }> }>; } });
  const bucket = documents.data?.buckets.find((item) => item.documentBucketId === selected);
  return <section className="card"><h2>Document Builder</h2><p>Authoritative bullet points and amendments remain separate from immutable generated draft versions.</p>{documents.isPending ? <p>Loading document buckets…</p> : documents.isError ? <p className="notice notice--bad">{documents.error.message}</p> : <><label className="field">Document bucket<select className="input" value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Select a bucket</option>{documents.data.buckets.map((item) => <option key={item.documentBucketId} value={item.documentBucketId}>{item.name}</option>)}</select></label>{bucket && <div className="grid-2"><div><h3>Source bullet points</h3><ol>{bucket.sourcePoints.map((point) => <li key={point.documentSourcePointId}>{point.content} <small>{point.sourceLabel}</small></li>)}</ol><h3>Amendments</h3><ol>{bucket.amendments.map((item) => <li key={item.documentAmendmentId}>{item.content}</li>)}</ol></div><div><label className="field">Generated draft prose<textarea className="textarea" value={content} onChange={(event) => setContent(event.target.value)} /></label><button className="button button--gold" disabled={!content.trim() || bucket.sourcePoints.length === 0} onClick={async () => { const response = await fetch("/api/admin/documents", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ content, documentBucketId: bucket.documentBucketId }) }); setMessage(response.ok ? "New immutable draft version created." : "Draft version could not be created."); if (response.ok) { setContent(""); await documents.refetch(); } }}>Create draft version</button><p>{bucket.drafts.length} existing draft version(s).</p></div></div>}</>}{message && <p className="notice" role="status">{message}</p>}</section>;
}

export function OperationsAdminPage({ screen }: { screen: PageManifestEntry }) {
  if (screen.path === "/admin/operations/releases") return <ReleaseManager />;
  return <div className="stack"><section className="card"><h2>Bounded operations</h2><p>Health, safe build identity, release records, and document generation use server-owned endpoints. Arbitrary shell execution is not accepted.</p><div className="action-row"><a className="button" href="/api/health">Public health</a><a className="button" href="/api/version">Build identity</a><a className="button button--gold" href="/admin/operations/releases">Release management</a></div></section><DocumentBuilder /></div>;
}
