import { createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { promisify } from "node:util";

const execute = promisify(execFile);
const repositoryRoot = resolve(import.meta.dirname, "../../..");
const outputDirectory = resolve(repositoryRoot, "artifacts/release-0.3.0/witness-remediation");
const forbiddenDisclaimer = ["Relation is edited through its owning canonical ", "foreign-key field or workflow."].join("");

async function fileEvidence(path: string, markers: string[] = []) {
  try {
    await access(path);
    const contents = await readFile(path);
    const text = contents.toString("utf8");
    return {
      path,
      exists: true,
      byteSize: contents.byteLength,
      sha256: createHash("sha256").update(contents).digest("hex"),
      markers: Object.fromEntries(markers.map((marker) => [marker, text.includes(marker)])),
    };
  } catch {
    return { path, exists: false, byteSize: null, sha256: null, markers: {} };
  }
}

async function repositoryMatches(pattern: string): Promise<string[]> {
  try {
    const { stdout } = await execute("rg", ["-n", "--hidden", "--glob", "!**/.git/**", "--glob", "!**/node_modules/**", "--glob", "!**/dist/**", "--glob", "!**/.next/**", pattern, "."], { cwd: repositoryRoot, maxBuffer: 16 * 1024 * 1024 });
    return stdout.trim() ? stdout.trim().split("\n") : [];
  } catch (error) {
    if (typeof error === "object" && error !== null && "code" in error && error.code === 1) return [];
    throw error;
  }
}

const disclaimerMatches = await repositoryMatches(forbiddenDisclaimer.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
const sourceEvidence = await Promise.all([
  fileEvidence("/home/bobby/Downloads/EIDOLON_ARCHITECT_WITNESS_GUIDE_CANONICAL_INPUT_2026-08-15.zip"),
  fileEvidence("/home/bobby/Downloads/witness_reward_mapping_decoy_riddle_data_only.html", ["APPROVED_CANDIDATE_BANK_AWAITING_MAPPING", "POSSIBLE_WITNESS_AWAITING_MAPPING"]),
  fileEvidence("/home/bobby/Downloads/ChatGPT-Outline Witness Compromises-20260826-1833 (2).md"),
  fileEvidence(resolve(repositoryRoot, "apps/web/src/data/architect-witness-guide/witnesses.json")),
  fileEvidence(resolve(repositoryRoot, "apps/web/src/data/architect-witness-guide/witness_defs.json")),
]);

let browserEvidence: Record<string, unknown> | null = null;
try {
  browserEvidence = JSON.parse(await readFile(resolve(repositoryRoot, "artifacts/release-0.3.0/owner-ui/owner-data-browser-evidence.json"), "utf8")) as Record<string, unknown>;
} catch { /* Browser evidence is generated by the required Chromium run. */ }
const browserAssertions = browserEvidence?.assertions as Record<string, unknown> | undefined;

const artifact = {
  schemaVersion: "final-witness-repository-and-ui-scans-v1",
  sourceInspection: sourceEvidence,
  forbiddenDisclaimerScan: {
    command: "rg -n --hidden with generated/build dependency exclusions",
    occurrenceCount: disclaimerMatches.length,
    matches: disclaimerMatches,
    status: disclaimerMatches.length === 0 ? "PASS" : "FAIL",
  },
  rawTokenPresentationScan: {
    browserArtifact: browserEvidence ? "../owner-ui/owner-data-browser-evidence.json" : null,
    chromiumStatus: browserEvidence?.status ?? "PENDING",
    occurrenceCount: browserAssertions?.rawOwnerTokenOccurrences ?? null,
    status: browserEvidence?.status === "PASS" && browserAssertions?.rawOwnerTokenOccurrences === 0 ? "PASS" : "PENDING",
  },
};
await mkdir(outputDirectory, { recursive: true });
await writeFile(resolve(outputDirectory, "repository-and-ui-scans.json"), `${JSON.stringify(artifact, null, 2)}\n`);
process.stdout.write(`${JSON.stringify(artifact, null, 2)}\n`);
if (disclaimerMatches.length) process.exitCode = 1;
