-- CreateEnum
CREATE TYPE "Alignment" AS ENUM ('ORDERED', 'CHAOS', 'NEUTRAL');

-- CreateEnum
CREATE TYPE "Faction" AS ENUM ('CONCORD', 'RUIN', 'SCHISM');

-- CreateEnum
CREATE TYPE "SizeClass" AS ENUM ('TINY', 'SMALL', 'MEDIUM', 'LARGE', 'EXTRA_LARGE');

-- CreateEnum
CREATE TYPE "PersonalityFamily" AS ENUM ('ACCOUNTABILITY', 'AMBIGUITY', 'ANGER', 'APPETITE', 'ATTACHMENT', 'AUTHENTICITY', 'AUTHORITY', 'AUTONOMY', 'BELONGING', 'BOUNDARIES', 'CARE', 'CHANGE', 'CLOSURE', 'COLLECTIVE_MEMORY', 'COMPASSION', 'COMPETITION', 'CONFORMITY', 'CONTROL', 'COOPERATION', 'COURAGE', 'CURIOSITY', 'DESIRE', 'DISCIPLINE', 'DISSENT', 'DOMINANCE', 'DOUBT', 'DUTY', 'EMBODIMENT', 'EMPATHY', 'ENVY', 'EQUANIMITY', 'EXILE', 'EXPOSURE', 'EXPRESSION', 'FAIRNESS', 'FAITH', 'FEAR', 'FORCE', 'FORGIVENESS', 'GRIEF', 'HIERARCHY', 'HOPE', 'HOSPITALITY', 'IMPULSE', 'INDIVIDUALITY', 'INTIMACY', 'LAND', 'LEGITIMACY', 'LOYALTY', 'MEANING', 'MEMORY', 'MERCY', 'MORTALITY', 'NOVELTY', 'PATIENCE', 'PERFECTION', 'PERSEVERANCE', 'PERSPECTIVE', 'PLEASURE', 'POSSESSION', 'POWER', 'PROTECTION', 'PURPOSE', 'REACTANCE', 'RECIPROCITY', 'RECOGNITION', 'REPAIR', 'REPUTATION', 'RESTRAINT', 'RISK', 'SCARCITY', 'SECRECY', 'SELF_KNOWLEDGE', 'SELF_REGARD', 'STATUS', 'STEWARDSHIP', 'TRADITION', 'TRUST', 'TRUTH', 'VENGEANCE');

-- CreateEnum
CREATE TYPE "LatitudinalZone" AS ENUM ('EQUATORIAL', 'TROPICS', 'TEMPERATE', 'TAIGA', 'POLAR');

-- CreateEnum
CREATE TYPE "CulturePoolId" AS ENUM ('CP01', 'CP02', 'CP03', 'CP04', 'CP05', 'CP06', 'CP07', 'CP08', 'CP09', 'CP10', 'CP11', 'CP12', 'CP13', 'CP14', 'CP15', 'CP16', 'CP17', 'CP18', 'CP19', 'CP20', 'CP21', 'CP22', 'CP23', 'CP24', 'CP25');

-- CreateEnum
CREATE TYPE "LeadershipModel" AS ENUM ('ASSEMBLY_PRIMACY', 'COLLECTIVE_EXECUTIVE', 'COUNCIL_PRIMACY', 'DUAL_EXECUTIVE', 'MILITARY_COMMAND', 'SACRED_OFFICE', 'SINGLE_EXECUTIVE');

-- CreateEnum
CREATE TYPE "SelectionMethod" AS ENUM ('APPOINTMENT', 'CLERGY_SELECTION', 'COOPTATION', 'CUSTOMARY_SUCCESSION', 'DIRECT_ELECTION', 'DIVINE_DESIGNATION', 'HEREDITARY', 'INDIRECT_ELECTION', 'MILITARY_ACCLAMATION', 'SORTITION');

-- CreateEnum
CREATE TYPE "SuccessionMode" AS ENUM ('APPOINTMENT', 'CLAN_OR_HOUSE_SELECTION', 'CLERGY_SELECTION', 'COUNCIL_COOPTATION', 'CUSTOMARY', 'ELECTION', 'HEREDITARY_DESIGNATED_HEIR', 'HEREDITARY_PRIMOGENITURE', 'MILITARY_ACCLAMATION', 'ROTATION');

-- CreateEnum
CREATE TYPE "OriginMode" AS ENUM ('BIOLOGICAL', 'ASSEMBLED', 'ELEMENTAL_CONDENSATION', 'HEAVENFALL', 'MANIFESTED', 'PIT_BORN', 'RESURRECTED', 'TRANSFORMATION', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "ReproductionMethod" AS ENUM ('AQUATIC_SPAWNING', 'BROOD_POUCH', 'EGG_BEARING', 'EGG_LAYING', 'EXTERNAL_SPAWNING', 'HERMAPHRODITIC_COCOON', 'LIVE_BIRTH', 'MAGICAL_GESTATION', 'PARTHENOGENESIS', 'SELF_FERTILIZING', 'NONE', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "JuvenileStage" AS ENUM ('AMMOCOETE_LARVA', 'AQUATIC_LARVA', 'AQUATIC_NYMPH', 'CALF', 'CALIBRATION_STAGE', 'CATERPILLAR', 'CHICK', 'CORE_FORM', 'DEPENDENT_CHILD', 'DEPENDENT_INFANT', 'DEPENDENT_YOUNG', 'ESSENCE_FORM', 'FIRST_SHIFT', 'FRY', 'HATCHLING', 'JUVENILE', 'LARVA', 'METAMORPHOSIS', 'NYMPH', 'PLANKTONIC_LARVA', 'POUCH_YOUNG', 'PUP', 'PUPA', 'SPIDERLING', 'TADPOLE', 'TRILOBITE_LARVA');

-- CreateEnum
CREATE TYPE "NurseryMode" AS ENUM ('NONE', 'GESTATIONAL_CARE', 'EGG_INCUBATION', 'BROOD_CARE', 'POUCH_CARE', 'AQUATIC_NURSERY', 'LARVAL_NURSERY', 'COLONY_NURSERY', 'CONSTRUCT_ASSEMBLY', 'ESSENCE_DEVELOPMENT', 'DEPENDENT_CHILDHOOD', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "LongevityClass" AS ENUM ('SHORT_LIVED', 'HUMAN_BASELINE', 'LONG_LIVED', 'EXTREMELY_LONG_LIVED', 'IN_PERPETUITY', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "NaturalMortalityMode" AS ENUM ('NORMAL', 'REDUCED', 'AGELESS', 'NONE', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "SoulDisposition" AS ENUM ('REINCARNATES', 'ONE_TIME_TRANSFERENCE', 'TERMINAL_BOUND', 'RETURNS_TO_WELL', 'DISSIPATES', 'NO_SOUL', 'SPECIAL_EXCEPTION', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "ContinuityGroupType" AS ENUM ('FAMILY', 'CLAN', 'HOUSE', 'BROOD', 'MAKER_LINE', 'ORDER', 'CHOIR', 'COVEN', 'PACK', 'COLONY', 'NONE', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "ContinuityPropagationMode" AS ENUM ('MATERNAL_DESCENT', 'PATERNAL_DESCENT', 'BILATERAL_DESCENT', 'MAKER_ASSIGNMENT', 'SIRE_LINE', 'ADOPTION', 'INITIATION', 'SPONSORSHIP', 'APPOINTMENT', 'CONTRACT', 'REINCARNATION_CONTINUITY', 'SELF_SELECTED', 'NONE', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "NameGenderBucket" AS ENUM ('FEMININE', 'MASCULINE', 'NEUTRAL');

-- CreateEnum
CREATE TYPE "FoodBroadCategory" AS ENUM ('ANIMAL', 'ARCANE_ESSENCE', 'ELEMENTAL', 'FUNGUS_DETRITUS', 'MINERAL_MATERIAL', 'NO_FEEDING', 'PLANT');

-- CreateEnum
CREATE TYPE "FoodSpecific" AS ENUM ('AIR_WIND', 'ALGAE_SEAWEED', 'ANGER', 'AQUATIC_PLANTS', 'ARTHROPODS', 'BAMBOO', 'BERRIES', 'BIRDS', 'BLOOD', 'BONE_MARROW', 'BREAD_PORRIDGE', 'CARRION', 'COLD_ICE', 'DAIRY', 'DESIRE', 'DETRITUS_COMPOST', 'DREAMS', 'EGGS', 'ELECTRICITY_STORM', 'EMOTION', 'ESSENCE_OF_FAITH', 'FEAR', 'FERMENTED_DRINK', 'FIRE', 'FISH', 'FLOWERS_POLLEN', 'FRUIT', 'FUNGI', 'GLASS_SAND', 'GRASSES', 'GRIEF', 'HERBS_SPICES', 'HONEY', 'INSECTS', 'LEAVES', 'LIGHT', 'MAGIC', 'MEMORY', 'METAL_ORE', 'MIXED_DIET', 'MOLLUSKS', 'MOONLIGHT', 'MUSIC_ATTENTION', 'NECROMANTIC_ESSENCE', 'NECTAR', 'NO_FEEDING', 'NUTS', 'OATHS_HONOR', 'OIL_FUEL', 'PLANKTON_KRILL', 'PREPARED_MEALS', 'RED_MEAT', 'REPTILES_AMPHIBIANS', 'ROOTS_TUBERS', 'SALT', 'SAP_RESIN', 'SEEDS_GRAINS', 'SHELLFISH_CRUSTACEANS', 'SIN', 'SMALL_GAME', 'STONE_CLAY', 'WATER', 'WOODY_BIOMASS', 'WORMS_LARVAE');

-- CreateEnum
CREATE TYPE "TerrainBroad" AS ENUM ('BUILT_ENVIRONMENT', 'COASTAL', 'DESERT', 'FOREST', 'FRESHWATER', 'GENERALIST', 'GRASSLAND', 'MOUNTAIN', 'OCEAN', 'POLAR_ICE', 'SUBTERRANEAN', 'WETLAND');

-- CreateEnum
CREATE TYPE "TerrainSpecific" AS ENUM ('ALPINE', 'BOG', 'BOREAL_FOREST', 'BURROW', 'CANOPY', 'CANYON', 'CASTLE', 'CAVE', 'CITY', 'CLIFF', 'CLOUD_FOREST', 'COASTAL_CLIFF', 'COLD_DESERT', 'CORAL_REEF', 'DELTA', 'DUNES', 'ESTUARY', 'FARMLAND', 'FJORD', 'FLOODPLAIN', 'FLOWERING_HABITAT', 'FOREST_EDGE', 'FOREST_FLOOR', 'GENERALIST', 'GLACIER', 'HOT_DESERT', 'ISLAND', 'KARST', 'KELP_FOREST', 'LAKE', 'MANGROVE', 'MARSH', 'MEADOW', 'MINE', 'MONTANE_FOREST', 'MUDFLAT', 'OASIS', 'OLD_GROWTH_FOREST', 'PACK_ICE', 'PELAGIC', 'PLATEAU', 'POND', 'PRAIRIE', 'RAIN_FOREST', 'RIVER', 'ROAD', 'RUINS', 'SAVANNA', 'SCRUBLAND', 'SEAGRASS_BED', 'SEA_CAVE', 'SHADOW_FOREST', 'SOIL', 'STEPPE', 'SWAMP', 'TEMPLE', 'TUNDRA', 'TUNNEL', 'UNDERGROUND_RIVER', 'VILLAGE', 'VOLCANIC', 'WOODLAND', 'WORKSHOP');

-- CreateEnum
CREATE TYPE "SourceType" AS ENUM ('BOOK', 'JOURNAL_ARTICLE', 'WEBPAGE', 'REPORT', 'THESIS', 'DATASET', 'ARCHIVE', 'INTERVIEW', 'AUDIOVISUAL', 'PRIMARY_DOCUMENT', 'OTHER');

-- CreateEnum
CREATE TYPE "ContributorType" AS ENUM ('AUTHOR', 'EDITOR', 'TRANSLATOR', 'DIRECTOR', 'ORGANIZATION', 'INTERVIEWEE', 'OTHER');

-- CreateEnum
CREATE TYPE "ResearchCategory" AS ENUM ('EXODUS_PROGRAM', 'REWARD', 'SPECIES', 'HISTORICAL_EVENT', 'CULTURAL_WOUND', 'PERSON', 'PLACE', 'INSTITUTION', 'ORGANIZATION', 'SYMBOL', 'TOME', 'TECHNOLOGY_OR_SYSTEM', 'OTHER');

-- CreateEnum
CREATE TYPE "DepartmentWitnessPathStatus" AS ENUM ('NORMAL', 'EXEMPT', 'EXCLUDED');

-- CreateEnum
CREATE TYPE "PuzzleSharedComponentId" AS ENUM ('PUZCMP-AUDIO-TRANSPORT', 'PUZCMP-MUSIC-NOTATION-RAIL', 'PUZCMP-RHYTHM-HAPTIC-TRACK', 'PUZCMP-TILE-SIGNAL', 'PUZCMP-LANTERN-LAYER-CONTROL', 'PUZCMP-GRID-VIEWPORT', 'PUZCMP-EIGHT-NEIGHBOR-NAV', 'PUZCMP-DIRECTIONAL-AUDIO-HAPTIC', 'PUZCMP-LOGIC-GRID', 'PUZCMP-SET-WORKBENCH', 'PUZCMP-DOCUMENT-COMPARE', 'PUZCMP-MATRIX-LAB', 'PUZCMP-IMAGE-TRANSFORM', 'PUZCMP-QR-BOUND-ROUTE', 'PUZCMP-COLOR-CHANNEL-LAB', 'PUZCMP-SHAPE-LAYER', 'PUZCMP-SLIDING-BLOCK-BOARD', 'PUZCMP-DRAG-CONNECTOR-BOARD', 'PUZCMP-MECHANISM-SIM', 'PUZCMP-POLYHEDRON-VIEWER', 'PUZCMP-NON3D-EQUIVALENT', 'PUZCMP-CHESS-REPLAY', 'PUZCMP-SPECTROGRAM', 'PUZCMP-TIMELINE-RESEARCH', 'PUZCMP-HINT-PANEL', 'PUZCMP-TIMER-BANNER', 'PUZCMP-ANSWER-SUBMISSION', 'PUZCMP-UNDO-RESET-HISTORY', 'PUZCMP-ACCESSIBILITY-MODE-SWITCHER', 'PUZCMP-PRINTABLE-WORKSHEET', 'PUZCMP-COLLABORATION-PACKET');

-- CreateEnum
CREATE TYPE "PuzzleFamily" AS ENUM ('TEXT_LANGUAGE_LITERARY', 'CRYPTO_NUMERIC_DATA', 'VISUAL_COLOR_OPTICAL', 'SPATIAL_FOLDING_GEOMETRY', 'AUDIO_MUSIC_SPECTRAL', 'LOGIC_CONSTRAINT', 'HISTORICAL_RESEARCH', 'CONSTRUCTION_SIMULATION', 'CROSS_MODAL');

-- CreateEnum
CREATE TYPE "PuzzleDifficultyTier" AS ENUM ('TIER_1_INITIATE', 'TIER_2_ADEPT', 'TIER_3_EXPERT', 'TIER_4_MASTER', 'TIER_5_ORDEAL');

-- CreateEnum
CREATE TYPE "CapabilityValueKind" AS ENUM ('BOOLEAN', 'SCORE', 'COUNTER', 'ENUM', 'REFERENCE');

-- CreateEnum
CREATE TYPE "CompanionKey" AS ENUM ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K');

-- CreateEnum
CREATE TYPE "RegionId" AS ENUM ('R01', 'R02', 'R03', 'R04', 'R05', 'R06', 'R07', 'R08', 'R09', 'R10', 'R11', 'R12', 'R13', 'R14', 'R15', 'R16', 'R17', 'R18', 'R19', 'R20', 'R21', 'R22', 'R23', 'R24', 'R25');

-- CreateEnum
CREATE TYPE "NameStatus" AS ENUM ('WORKING', 'CANONICAL');

-- CreateEnum
CREATE TYPE "SettlementClassification" AS ENUM ('HAMLET', 'VILLAGE', 'TOWN', 'CITY', 'METROPOLIS');

-- CreateEnum
CREATE TYPE "SettlementSurfaceType" AS ENUM ('LAND', 'COASTAL_LAND', 'SHALLOW_WATER', 'REEF', 'FLOATING_ISLAND', 'UNDERWATER', 'ICE', 'WETLAND', 'LAKE', 'DELTA');

-- CreateEnum
CREATE TYPE "CharacterType" AS ENUM ('MAJOR', 'SUPPORTING', 'EXTRA');

-- CreateEnum
CREATE TYPE "LatticeId" AS ENUM ('L01', 'L02', 'L03', 'L04', 'L05', 'L06', 'L07', 'L08', 'L09', 'L10', 'L11', 'L12', 'L13', 'L14', 'L15', 'L16', 'L17', 'L18', 'L19', 'L20', 'L21', 'L22', 'L23', 'L24', 'L25');

-- CreateEnum
CREATE TYPE "SettlementPopulationEventType" AS ENUM ('FOUNDING', 'GROWTH', 'MIGRATION_IN', 'MIGRATION_OUT');

-- CreateEnum
CREATE TYPE "CapabilityOperation" AS ENUM ('SET', 'ADD');

-- CreateEnum
CREATE TYPE "CapabilityRequirementOperator" AS ENUM ('EXISTS', 'EQ', 'NEQ', 'GT', 'GTE', 'LT', 'LTE');

-- CreateEnum
CREATE TYPE "RewardEvidenceKind" AS ENUM ('RUMOR', 'EVIDENCE', 'PROOF', 'DOUBT', 'CONTRADICTION', 'REFUTATION');

-- CreateEnum
CREATE TYPE "KnowledgeBaseBlockKind" AS ENUM ('HEADING', 'PARAGRAPH', 'QUOTE', 'LIST');

-- CreateEnum
CREATE TYPE "CalendarTrigger" AS ENUM ('CONJUNCTION_BEGINS', 'CONJUNCTION_DEADLINE', 'BEACON_PREPARE', 'BEACON_WARNING');

-- CreateEnum
CREATE TYPE "ArkStatus" AS ENUM ('OPERATIONAL', 'CANNIBALIZED', 'DAMAGED', 'DESTROYED');

-- CreateEnum
CREATE TYPE "DefinitionType" AS ENUM ('INTERNAL', 'EXTERNAL');

-- CreateEnum
CREATE TYPE "Holiday" AS ENUM ('DEEPWATCH', 'THAWMARCH', 'GOLDTIDE', 'VEILFALL');

-- CreateEnum
CREATE TYPE "EntityType" AS ENUM ('CULTURE', 'CHARACTER', 'PROTAGONIST', 'ANTAGONIST', 'WITNESS', 'ARCHITECT', 'DEPARTMENT', 'SPECIES', 'SPECIES_GROUP', 'BREED', 'PERSONALITY_EXPRESSION', 'TIMELINE_EVENT', 'INTERLUDE', 'INTERLUDE_SUBSTITUTION', 'PILLAR', 'LESSON', 'TRANSITION', 'LAYETTE', 'ARK', 'CONSTELLATION', 'LEGENDARY_REWARD', 'SOUL', 'POINT_OF_INTEREST', 'SITE', 'SETTLEMENT', 'MATRIX', 'COMPANION', 'TOME', 'DEFINITION', 'KNOWLEDGE_BASE_ITEM', 'CAPABILITY_DEFINITION', 'ACHIEVEMENT_DEFINITION', 'SOURCE', 'CITATION', 'AUTHORED_NARRATIVE', 'NPC_CONVERSATION_GRAPH');

-- CreateEnum
CREATE TYPE "Heirloom" AS ENUM ('NECKLACE', 'BRACELET', 'EARRINGS', 'CLOAK_CLASP', 'LIGHTER', 'POCKETWATCH', 'COIN_HEAD_BLACKENED', 'COIN_TAIL_BLACKENED', 'RING', 'TATTOO', 'BIRTHMARK', 'BROOCH', 'HAIR_BARRETTE', 'BELT_BUCKLE', 'BACKPACK_CLASP');

-- CreateEnum
CREATE TYPE "AgeEligibility" AS ENUM ('ADULT_18_PLUS', 'MINOR_14_17_GUARDIAN_CONSENTED');

-- CreateEnum
CREATE TYPE "FriendInvitationRequestStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'INVITED');

-- CreateEnum
CREATE TYPE "ExternalBulkApiState" AS ENUM ('OFF', 'ON');

-- CreateEnum
CREATE TYPE "MembershipGrantSource" AS ENUM ('SUBSCRIPTION', 'DONATION');

-- CreateEnum
CREATE TYPE "PerkStatus" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "PaymentProvider" AS ENUM ('STRIPE');

-- CreateEnum
CREATE TYPE "FulfillmentProvider" AS ENUM ('PRINTFUL');

-- CreateEnum
CREATE TYPE "ReleaseNotesStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'SUPERSEDED');

-- CreateEnum
CREATE TYPE "ReleaseAudience" AS ENUM ('PLAYERS', 'OPERATORS', 'BOTH');

-- CreateEnum
CREATE TYPE "ReleaseNoteCategory" AS ENUM ('ADDED', 'CHANGED', 'FIXED', 'SECURITY', 'KNOWN_ISSUE');

-- CreateEnum
CREATE TYPE "KnowledgeBaseDisclosureMode" AS ENUM ('APPEND_BLOCKS', 'INSERT_AFTER_BLOCK', 'REPLACE_BLOCK', 'REPLACE_ENTRY');

-- CreateEnum
CREATE TYPE "PuzzleHintKind" AS ENUM ('DIRECTIONAL', 'GUIDED');

-- CreateEnum
CREATE TYPE "BulkOperation" AS ENUM ('QUERY', 'CREATE', 'UPDATE', 'DELETE', 'IMPORT');

-- CreateEnum
CREATE TYPE "ImportAliasDisposition" AS ENUM ('DIRECT', 'ALIASED');

-- CreateEnum
CREATE TYPE "ImportResultState" AS ENUM ('UNCHANGED', 'CHANGED', 'FAILED');

-- CreateEnum
CREATE TYPE "MembershipRevocationReason" AS ENUM ('DONATION_REFUND');

-- CreateEnum
CREATE TYPE "ManagedAssetMediaKind" AS ENUM ('IMAGE', 'AUDIO', 'VIDEO');

-- CreateEnum
CREATE TYPE "PromptFamily" AS ENUM ('IMAGE', 'MUSIC', 'PUZZLE', 'NAMING');

-- CreateEnum
CREATE TYPE "PromptStatus" AS ENUM ('OUTSTANDING', 'READY', 'COMPLETED');

-- CreateEnum
CREATE TYPE "Loquacity" AS ENUM ('LIGHT_BANTER', 'TALKATIVE', 'TO_THE_POINT');

-- CreateEnum
CREATE TYPE "EmotionalTemperature" AS ENUM ('COMPOSED', 'IRRITABLE', 'JOYFUL');

-- CreateEnum
CREATE TYPE "OutlookOrientation" AS ENUM ('NEUTRAL', 'OPTIMISTIC', 'PESSIMISTIC');

-- CreateEnum
CREATE TYPE "CollaborativePosture" AS ENUM ('HELPFUL', 'JUST_ENOUGH', 'WITHHOLDING');

-- CreateEnum
CREATE TYPE "SpeciesResearchDimension" AS ENUM ('ADMINISTRATION_MODE', 'STRUCTURE_ORIENTATION', 'OPERATING_STYLE', 'MOTIVATION', 'AUTHORITY_SOURCE', 'LEGITIMACY_BASIS', 'ALLOCATION_MODE', 'OWNERSHIP_MODE', 'LOQUACITY', 'EMOTIONAL_TEMPERATURE', 'OUTLOOK_ORIENTATION', 'COLLABORATIVE_POSTURE');

-- CreateEnum
CREATE TYPE "SpeciesResearchReviewStatus" AS ENUM ('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED');

-- CreateEnum
CREATE TYPE "SpeciesResearchProvenanceKind" AS ENUM ('MANUAL', 'IMPORT');

-- CreateEnum
CREATE TYPE "SpeciesDimensionValue" AS ENUM ('CENTRALIZED', 'DELEGATED', 'DISTRIBUTED', 'ORDERED', 'NEUTRAL', 'CHAOS', 'TEAMWORK', 'SITUATIONAL', 'SOLO', 'ALTRUISTIC', 'RECIPROCAL', 'SELFISH', 'APPOINTMENT', 'DIVINE_MANDATE', 'ELECTION', 'ANCESTRAL', 'CHARTERED', 'MARTIAL', 'CUSTOMARY', 'MARKET', 'PLANNED', 'COMMON_USE', 'SHARED_TITLE', 'SINGLE_ENTITY', 'LIGHT_BANTER', 'TALKATIVE', 'TO_THE_POINT', 'COMPOSED', 'IRRITABLE', 'JOYFUL', 'OPTIMISTIC', 'PESSIMISTIC', 'HELPFUL', 'JUST_ENOUGH', 'WITHHOLDING');

-- AlterEnum
BEGIN;
CREATE TYPE "CitationQuality_new" AS ENUM ('VERY_LOW', 'LOW', 'MODERATE', 'HIGH', 'VERY_HIGH');
ALTER TABLE "Citation" ALTER COLUMN "quality" TYPE "CitationQuality_new" USING ("quality"::text::"CitationQuality_new");
ALTER TABLE "Research" ALTER COLUMN "citationQuality" TYPE "CitationQuality_new" USING ("citationQuality"::text::"CitationQuality_new");
ALTER TYPE "CitationQuality" RENAME TO "CitationQuality_old";
ALTER TYPE "CitationQuality_new" RENAME TO "CitationQuality";
DROP TYPE "public"."CitationQuality_old";
COMMIT;

-- AlterTable
ALTER TABLE "BetaInviteRequest"
ALTER COLUMN "status" DROP DEFAULT,
ALTER COLUMN "status" TYPE "FriendInvitationRequestStatus"
USING ("status"::text::"FriendInvitationRequestStatus"),
ALTER COLUMN "status" SET DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE "CapabilityDefinition"
ALTER COLUMN "valueType" TYPE "CapabilityValueKind"
USING ("valueType"::text::"CapabilityValueKind");

-- AlterTable
ALTER TABLE "User"
ALTER COLUMN "eligibilityStatus" TYPE "AgeEligibility"
USING ("eligibilityStatus"::text::"AgeEligibility");

-- DropEnum
DROP TYPE "AccountEligibilityStatus";

-- DropEnum
DROP TYPE "BetaInviteRequestStatus";

-- DropEnum
DROP TYPE "CapabilityValueType";
