/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiReleasesRouteImport } from './routes/api/releases'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as FeaturesFreeToPlayRouteImport } from './routes/features.free-to-play'
import { Route as ApiAccountMembershipRouteImport } from './routes/api/account/membership'
import { Route as ApiAccountSettingsRouteImport } from './routes/api/account/settings'
import { Route as ApiAdminCampaignRouteImport } from './routes/api/admin/campaign'
import { Route as ApiAdminDocumentsRouteImport } from './routes/api/admin/documents'
import { Route as ApiAdminReleasesRouteImport } from './routes/api/admin/releases'
import { Route as ApiAtlasCatalogRouteImport } from './routes/api/atlas/catalog'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBetaInvitationsRedeemRouteImport } from './routes/api/beta-invitations/redeem'
import { Route as ApiBetaInvitationsRequestRouteImport } from './routes/api/beta-invitations/request'
import { Route as ApiDonationsCheckoutRouteImport } from './routes/api/donations/checkout'
import { Route as ApiPlayerAccessRouteImport } from './routes/api/player/access'
import { Route as ApiPlayerCalendarRouteImport } from './routes/api/player/calendar'
import { Route as ApiPlayerPuzzlesRouteImport } from './routes/api/player/puzzles'
import { Route as ApiPlayerRuntimeRouteImport } from './routes/api/player/runtime'
import { Route as ApiStoreCatalogRouteImport } from './routes/api/store/catalog'
import { Route as ApiStoreCheckoutRouteImport } from './routes/api/store/checkout'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiAccountOrdersIndexRouteImport } from './routes/api/account/orders/index'
import { Route as ApiAccountOrdersOrderIdRouteImport } from './routes/api/account/orders/$orderId'
import { Route as ApiAccountSessionsIndexRouteImport } from './routes/api/account/sessions/index'
import { Route as ApiAccountSessionsRevokeAllOtherRouteImport } from './routes/api/account/sessions/revoke-all-other'
import { Route as ApiAccountSessionsRevokeOtherRouteImport } from './routes/api/account/sessions/revoke-other'
import { Route as ApiAdminAccountsIndexRouteImport } from './routes/api/admin/accounts/index'
import { Route as ApiAdminAccountsUserIdRouteImport } from './routes/api/admin/accounts/$userId'
import { Route as ApiAdminAssetsIndexRouteImport } from './routes/api/admin/assets/index'
import { Route as ApiAdminBetaInvitationsIndexRouteImport } from './routes/api/admin/beta-invitations/index'
import { Route as ApiAdminCommerceIndexRouteImport } from './routes/api/admin/commerce/index'
import { Route as ApiAdminPerksIndexRouteImport } from './routes/api/admin/perks/index'
import { Route as ApiAdminPerksPerkIdRouteImport } from './routes/api/admin/perks/$perkId'
import { Route as ApiAdminPromptsIndexRouteImport } from './routes/api/admin/prompts/index'
import { Route as ApiAdminPuzzlesBlueprintsRouteImport } from './routes/api/admin/puzzles/blueprints'
import { Route as ApiAdminSettlementsIndexRouteImport } from './routes/api/admin/settlements/index'
import { Route as ApiAdminSettlementsCompleteNamingRouteImport } from './routes/api/admin/settlements/complete-naming'
import { Route as ApiAdminSettlementsFoundCityRouteImport } from './routes/api/admin/settlements/found-city'
import { Route as ApiAdminSettlementsMigrateRouteImport } from './routes/api/admin/settlements/migrate'
import { Route as ApiAdminAccountsUserIdRoleRouteImport } from './routes/api/admin/accounts/$userId/role'
import { Route as ApiAdminBetaInvitationsIdApproveRouteImport } from './routes/api/admin/beta-invitations/$id/approve'
import { Route as ApiAdminBetaInvitationsIdRejectRouteImport } from './routes/api/admin/beta-invitations/$id/reject'
import { Route as ApiAdminDataEntityKeyImportRouteImport } from './routes/api/admin/data/$entityKey/import'
import { Route as ApiAdminReleasesIdPublishRouteImport } from './routes/api/admin/releases/$id/publish'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleasesRoute = ApiReleasesRouteImport.update({
  id: '/api/releases',
  path: '/api/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesFreeToPlayRoute = FeaturesFreeToPlayRouteImport.update({
  id: '/features/free-to-play',
  path: '/features/free-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountMembershipRoute = ApiAccountMembershipRouteImport.update({
  id: '/api/account/membership',
  path: '/api/account/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountSettingsRoute = ApiAccountSettingsRouteImport.update({
  id: '/api/account/settings',
  path: '/api/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCampaignRoute = ApiAdminCampaignRouteImport.update({
  id: '/api/admin/campaign',
  path: '/api/admin/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDocumentsRoute = ApiAdminDocumentsRouteImport.update({
  id: '/api/admin/documents',
  path: '/api/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReleasesRoute = ApiAdminReleasesRouteImport.update({
  id: '/api/admin/releases',
  path: '/api/admin/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAtlasCatalogRoute = ApiAtlasCatalogRouteImport.update({
  id: '/api/atlas/catalog',
  path: '/api/atlas/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetaInvitationsRedeemRoute =
  ApiBetaInvitationsRedeemRouteImport.update({
    id: '/api/beta-invitations/redeem',
    path: '/api/beta-invitations/redeem',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBetaInvitationsRequestRoute =
  ApiBetaInvitationsRequestRouteImport.update({
    id: '/api/beta-invitations/request',
    path: '/api/beta-invitations/request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDonationsCheckoutRoute = ApiDonationsCheckoutRouteImport.update({
  id: '/api/donations/checkout',
  path: '/api/donations/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerAccessRoute = ApiPlayerAccessRouteImport.update({
  id: '/api/player/access',
  path: '/api/player/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerCalendarRoute = ApiPlayerCalendarRouteImport.update({
  id: '/api/player/calendar',
  path: '/api/player/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerPuzzlesRoute = ApiPlayerPuzzlesRouteImport.update({
  id: '/api/player/puzzles',
  path: '/api/player/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayerRuntimeRoute = ApiPlayerRuntimeRouteImport.update({
  id: '/api/player/runtime',
  path: '/api/player/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreCatalogRoute = ApiStoreCatalogRouteImport.update({
  id: '/api/store/catalog',
  path: '/api/store/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreCheckoutRoute = ApiStoreCheckoutRouteImport.update({
  id: '/api/store/checkout',
  path: '/api/store/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountOrdersIndexRoute = ApiAccountOrdersIndexRouteImport.update({
  id: '/api/account/orders/',
  path: '/api/account/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountOrdersOrderIdRoute = ApiAccountOrdersOrderIdRouteImport.update({
  id: '/api/account/orders/$orderId',
  path: '/api/account/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountSessionsIndexRoute = ApiAccountSessionsIndexRouteImport.update({
  id: '/api/account/sessions/',
  path: '/api/account/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountSessionsRevokeAllOtherRoute =
  ApiAccountSessionsRevokeAllOtherRouteImport.update({
    id: '/api/account/sessions/revoke-all-other',
    path: '/api/account/sessions/revoke-all-other',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountSessionsRevokeOtherRoute =
  ApiAccountSessionsRevokeOtherRouteImport.update({
    id: '/api/account/sessions/revoke-other',
    path: '/api/account/sessions/revoke-other',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAccountsIndexRoute = ApiAdminAccountsIndexRouteImport.update({
  id: '/api/admin/accounts/',
  path: '/api/admin/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAccountsUserIdRoute = ApiAdminAccountsUserIdRouteImport.update({
  id: '/api/admin/accounts/$userId',
  path: '/api/admin/accounts/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAssetsIndexRoute = ApiAdminAssetsIndexRouteImport.update({
  id: '/api/admin/assets/',
  path: '/api/admin/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBetaInvitationsIndexRoute =
  ApiAdminBetaInvitationsIndexRouteImport.update({
    id: '/api/admin/beta-invitations/',
    path: '/api/admin/beta-invitations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminCommerceIndexRoute = ApiAdminCommerceIndexRouteImport.update({
  id: '/api/admin/commerce/',
  path: '/api/admin/commerce/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPerksIndexRoute = ApiAdminPerksIndexRouteImport.update({
  id: '/api/admin/perks/',
  path: '/api/admin/perks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPerksPerkIdRoute = ApiAdminPerksPerkIdRouteImport.update({
  id: '/api/admin/perks/$perkId',
  path: '/api/admin/perks/$perkId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPromptsIndexRoute = ApiAdminPromptsIndexRouteImport.update({
  id: '/api/admin/prompts/',
  path: '/api/admin/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPuzzlesBlueprintsRoute =
  ApiAdminPuzzlesBlueprintsRouteImport.update({
    id: '/api/admin/puzzles/blueprints',
    path: '/api/admin/puzzles/blueprints',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSettlementsIndexRoute =
  ApiAdminSettlementsIndexRouteImport.update({
    id: '/api/admin/settlements/',
    path: '/api/admin/settlements/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSettlementsCompleteNamingRoute =
  ApiAdminSettlementsCompleteNamingRouteImport.update({
    id: '/api/admin/settlements/complete-naming',
    path: '/api/admin/settlements/complete-naming',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSettlementsFoundCityRoute =
  ApiAdminSettlementsFoundCityRouteImport.update({
    id: '/api/admin/settlements/found-city',
    path: '/api/admin/settlements/found-city',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSettlementsMigrateRoute =
  ApiAdminSettlementsMigrateRouteImport.update({
    id: '/api/admin/settlements/migrate',
    path: '/api/admin/settlements/migrate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAccountsUserIdRoleRoute =
  ApiAdminAccountsUserIdRoleRouteImport.update({
    id: '/role',
    path: '/role',
    getParentRoute: () => ApiAdminAccountsUserIdRoute,
  } as any)
const ApiAdminBetaInvitationsIdApproveRoute =
  ApiAdminBetaInvitationsIdApproveRouteImport.update({
    id: '/api/admin/beta-invitations/$id/approve',
    path: '/api/admin/beta-invitations/$id/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminBetaInvitationsIdRejectRoute =
  ApiAdminBetaInvitationsIdRejectRouteImport.update({
    id: '/api/admin/beta-invitations/$id/reject',
    path: '/api/admin/beta-invitations/$id/reject',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminDataEntityKeyImportRoute =
  ApiAdminDataEntityKeyImportRouteImport.update({
    id: '/api/admin/data/$entityKey/import',
    path: '/api/admin/data/$entityKey/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminReleasesIdPublishRoute =
  ApiAdminReleasesIdPublishRouteImport.update({
    id: '/$id/publish',
    path: '/$id/publish',
    getParentRoute: () => ApiAdminReleasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRoute
  '/api/releases': typeof ApiReleasesRoute
  '/api/version': typeof ApiVersionRoute
  '/features/free-to-play': typeof FeaturesFreeToPlayRoute
  '/api/account/membership': typeof ApiAccountMembershipRoute
  '/api/account/settings': typeof ApiAccountSettingsRoute
  '/api/admin/campaign': typeof ApiAdminCampaignRoute
  '/api/admin/documents': typeof ApiAdminDocumentsRoute
  '/api/admin/releases': typeof ApiAdminReleasesRouteWithChildren
  '/api/atlas/catalog': typeof ApiAtlasCatalogRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta-invitations/redeem': typeof ApiBetaInvitationsRedeemRoute
  '/api/beta-invitations/request': typeof ApiBetaInvitationsRequestRoute
  '/api/donations/checkout': typeof ApiDonationsCheckoutRoute
  '/api/player/access': typeof ApiPlayerAccessRoute
  '/api/player/calendar': typeof ApiPlayerCalendarRoute
  '/api/player/puzzles': typeof ApiPlayerPuzzlesRoute
  '/api/player/runtime': typeof ApiPlayerRuntimeRoute
  '/api/store/catalog': typeof ApiStoreCatalogRoute
  '/api/store/checkout': typeof ApiStoreCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/account/orders/$orderId': typeof ApiAccountOrdersOrderIdRoute
  '/api/account/sessions/revoke-all-other': typeof ApiAccountSessionsRevokeAllOtherRoute
  '/api/account/sessions/revoke-other': typeof ApiAccountSessionsRevokeOtherRoute
  '/api/admin/accounts/$userId': typeof ApiAdminAccountsUserIdRouteWithChildren
  '/api/admin/perks/$perkId': typeof ApiAdminPerksPerkIdRoute
  '/api/admin/puzzles/blueprints': typeof ApiAdminPuzzlesBlueprintsRoute
  '/api/admin/settlements/complete-naming': typeof ApiAdminSettlementsCompleteNamingRoute
  '/api/admin/settlements/found-city': typeof ApiAdminSettlementsFoundCityRoute
  '/api/admin/settlements/migrate': typeof ApiAdminSettlementsMigrateRoute
  '/api/account/orders/': typeof ApiAccountOrdersIndexRoute
  '/api/account/sessions/': typeof ApiAccountSessionsIndexRoute
  '/api/admin/accounts/': typeof ApiAdminAccountsIndexRoute
  '/api/admin/assets/': typeof ApiAdminAssetsIndexRoute
  '/api/admin/beta-invitations/': typeof ApiAdminBetaInvitationsIndexRoute
  '/api/admin/commerce/': typeof ApiAdminCommerceIndexRoute
  '/api/admin/perks/': typeof ApiAdminPerksIndexRoute
  '/api/admin/prompts/': typeof ApiAdminPromptsIndexRoute
  '/api/admin/settlements/': typeof ApiAdminSettlementsIndexRoute
  '/api/admin/accounts/$userId/role': typeof ApiAdminAccountsUserIdRoleRoute
  '/api/admin/beta-invitations/$id/approve': typeof ApiAdminBetaInvitationsIdApproveRoute
  '/api/admin/beta-invitations/$id/reject': typeof ApiAdminBetaInvitationsIdRejectRoute
  '/api/admin/data/$entityKey/import': typeof ApiAdminDataEntityKeyImportRoute
  '/api/admin/releases/$id/publish': typeof ApiAdminReleasesIdPublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRoute
  '/api/releases': typeof ApiReleasesRoute
  '/api/version': typeof ApiVersionRoute
  '/features/free-to-play': typeof FeaturesFreeToPlayRoute
  '/api/account/membership': typeof ApiAccountMembershipRoute
  '/api/account/settings': typeof ApiAccountSettingsRoute
  '/api/admin/campaign': typeof ApiAdminCampaignRoute
  '/api/admin/documents': typeof ApiAdminDocumentsRoute
  '/api/admin/releases': typeof ApiAdminReleasesRouteWithChildren
  '/api/atlas/catalog': typeof ApiAtlasCatalogRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta-invitations/redeem': typeof ApiBetaInvitationsRedeemRoute
  '/api/beta-invitations/request': typeof ApiBetaInvitationsRequestRoute
  '/api/donations/checkout': typeof ApiDonationsCheckoutRoute
  '/api/player/access': typeof ApiPlayerAccessRoute
  '/api/player/calendar': typeof ApiPlayerCalendarRoute
  '/api/player/puzzles': typeof ApiPlayerPuzzlesRoute
  '/api/player/runtime': typeof ApiPlayerRuntimeRoute
  '/api/store/catalog': typeof ApiStoreCatalogRoute
  '/api/store/checkout': typeof ApiStoreCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/account/orders/$orderId': typeof ApiAccountOrdersOrderIdRoute
  '/api/account/sessions/revoke-all-other': typeof ApiAccountSessionsRevokeAllOtherRoute
  '/api/account/sessions/revoke-other': typeof ApiAccountSessionsRevokeOtherRoute
  '/api/admin/accounts/$userId': typeof ApiAdminAccountsUserIdRouteWithChildren
  '/api/admin/perks/$perkId': typeof ApiAdminPerksPerkIdRoute
  '/api/admin/puzzles/blueprints': typeof ApiAdminPuzzlesBlueprintsRoute
  '/api/admin/settlements/complete-naming': typeof ApiAdminSettlementsCompleteNamingRoute
  '/api/admin/settlements/found-city': typeof ApiAdminSettlementsFoundCityRoute
  '/api/admin/settlements/migrate': typeof ApiAdminSettlementsMigrateRoute
  '/api/account/orders': typeof ApiAccountOrdersIndexRoute
  '/api/account/sessions': typeof ApiAccountSessionsIndexRoute
  '/api/admin/accounts': typeof ApiAdminAccountsIndexRoute
  '/api/admin/assets': typeof ApiAdminAssetsIndexRoute
  '/api/admin/beta-invitations': typeof ApiAdminBetaInvitationsIndexRoute
  '/api/admin/commerce': typeof ApiAdminCommerceIndexRoute
  '/api/admin/perks': typeof ApiAdminPerksIndexRoute
  '/api/admin/prompts': typeof ApiAdminPromptsIndexRoute
  '/api/admin/settlements': typeof ApiAdminSettlementsIndexRoute
  '/api/admin/accounts/$userId/role': typeof ApiAdminAccountsUserIdRoleRoute
  '/api/admin/beta-invitations/$id/approve': typeof ApiAdminBetaInvitationsIdApproveRoute
  '/api/admin/beta-invitations/$id/reject': typeof ApiAdminBetaInvitationsIdRejectRoute
  '/api/admin/data/$entityKey/import': typeof ApiAdminDataEntityKeyImportRoute
  '/api/admin/releases/$id/publish': typeof ApiAdminReleasesIdPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/contact': typeof ApiContactRoute
  '/api/health': typeof ApiHealthRoute
  '/api/releases': typeof ApiReleasesRoute
  '/api/version': typeof ApiVersionRoute
  '/features/free-to-play': typeof FeaturesFreeToPlayRoute
  '/api/account/membership': typeof ApiAccountMembershipRoute
  '/api/account/settings': typeof ApiAccountSettingsRoute
  '/api/admin/campaign': typeof ApiAdminCampaignRoute
  '/api/admin/documents': typeof ApiAdminDocumentsRoute
  '/api/admin/releases': typeof ApiAdminReleasesRouteWithChildren
  '/api/atlas/catalog': typeof ApiAtlasCatalogRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta-invitations/redeem': typeof ApiBetaInvitationsRedeemRoute
  '/api/beta-invitations/request': typeof ApiBetaInvitationsRequestRoute
  '/api/donations/checkout': typeof ApiDonationsCheckoutRoute
  '/api/player/access': typeof ApiPlayerAccessRoute
  '/api/player/calendar': typeof ApiPlayerCalendarRoute
  '/api/player/puzzles': typeof ApiPlayerPuzzlesRoute
  '/api/player/runtime': typeof ApiPlayerRuntimeRoute
  '/api/store/catalog': typeof ApiStoreCatalogRoute
  '/api/store/checkout': typeof ApiStoreCheckoutRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/account/orders/$orderId': typeof ApiAccountOrdersOrderIdRoute
  '/api/account/sessions/revoke-all-other': typeof ApiAccountSessionsRevokeAllOtherRoute
  '/api/account/sessions/revoke-other': typeof ApiAccountSessionsRevokeOtherRoute
  '/api/admin/accounts/$userId': typeof ApiAdminAccountsUserIdRouteWithChildren
  '/api/admin/perks/$perkId': typeof ApiAdminPerksPerkIdRoute
  '/api/admin/puzzles/blueprints': typeof ApiAdminPuzzlesBlueprintsRoute
  '/api/admin/settlements/complete-naming': typeof ApiAdminSettlementsCompleteNamingRoute
  '/api/admin/settlements/found-city': typeof ApiAdminSettlementsFoundCityRoute
  '/api/admin/settlements/migrate': typeof ApiAdminSettlementsMigrateRoute
  '/api/account/orders/': typeof ApiAccountOrdersIndexRoute
  '/api/account/sessions/': typeof ApiAccountSessionsIndexRoute
  '/api/admin/accounts/': typeof ApiAdminAccountsIndexRoute
  '/api/admin/assets/': typeof ApiAdminAssetsIndexRoute
  '/api/admin/beta-invitations/': typeof ApiAdminBetaInvitationsIndexRoute
  '/api/admin/commerce/': typeof ApiAdminCommerceIndexRoute
  '/api/admin/perks/': typeof ApiAdminPerksIndexRoute
  '/api/admin/prompts/': typeof ApiAdminPromptsIndexRoute
  '/api/admin/settlements/': typeof ApiAdminSettlementsIndexRoute
  '/api/admin/accounts/$userId/role': typeof ApiAdminAccountsUserIdRoleRoute
  '/api/admin/beta-invitations/$id/approve': typeof ApiAdminBetaInvitationsIdApproveRoute
  '/api/admin/beta-invitations/$id/reject': typeof ApiAdminBetaInvitationsIdRejectRoute
  '/api/admin/data/$entityKey/import': typeof ApiAdminDataEntityKeyImportRoute
  '/api/admin/releases/$id/publish': typeof ApiAdminReleasesIdPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/contact'
    | '/api/health'
    | '/api/releases'
    | '/api/version'
    | '/features/free-to-play'
    | '/api/account/membership'
    | '/api/account/settings'
    | '/api/admin/campaign'
    | '/api/admin/documents'
    | '/api/admin/releases'
    | '/api/atlas/catalog'
    | '/api/auth/$'
    | '/api/beta-invitations/redeem'
    | '/api/beta-invitations/request'
    | '/api/donations/checkout'
    | '/api/player/access'
    | '/api/player/calendar'
    | '/api/player/puzzles'
    | '/api/player/runtime'
    | '/api/store/catalog'
    | '/api/store/checkout'
    | '/api/stripe/webhook'
    | '/api/account/orders/$orderId'
    | '/api/account/sessions/revoke-all-other'
    | '/api/account/sessions/revoke-other'
    | '/api/admin/accounts/$userId'
    | '/api/admin/perks/$perkId'
    | '/api/admin/puzzles/blueprints'
    | '/api/admin/settlements/complete-naming'
    | '/api/admin/settlements/found-city'
    | '/api/admin/settlements/migrate'
    | '/api/account/orders/'
    | '/api/account/sessions/'
    | '/api/admin/accounts/'
    | '/api/admin/assets/'
    | '/api/admin/beta-invitations/'
    | '/api/admin/commerce/'
    | '/api/admin/perks/'
    | '/api/admin/prompts/'
    | '/api/admin/settlements/'
    | '/api/admin/accounts/$userId/role'
    | '/api/admin/beta-invitations/$id/approve'
    | '/api/admin/beta-invitations/$id/reject'
    | '/api/admin/data/$entityKey/import'
    | '/api/admin/releases/$id/publish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/contact'
    | '/api/health'
    | '/api/releases'
    | '/api/version'
    | '/features/free-to-play'
    | '/api/account/membership'
    | '/api/account/settings'
    | '/api/admin/campaign'
    | '/api/admin/documents'
    | '/api/admin/releases'
    | '/api/atlas/catalog'
    | '/api/auth/$'
    | '/api/beta-invitations/redeem'
    | '/api/beta-invitations/request'
    | '/api/donations/checkout'
    | '/api/player/access'
    | '/api/player/calendar'
    | '/api/player/puzzles'
    | '/api/player/runtime'
    | '/api/store/catalog'
    | '/api/store/checkout'
    | '/api/stripe/webhook'
    | '/api/account/orders/$orderId'
    | '/api/account/sessions/revoke-all-other'
    | '/api/account/sessions/revoke-other'
    | '/api/admin/accounts/$userId'
    | '/api/admin/perks/$perkId'
    | '/api/admin/puzzles/blueprints'
    | '/api/admin/settlements/complete-naming'
    | '/api/admin/settlements/found-city'
    | '/api/admin/settlements/migrate'
    | '/api/account/orders'
    | '/api/account/sessions'
    | '/api/admin/accounts'
    | '/api/admin/assets'
    | '/api/admin/beta-invitations'
    | '/api/admin/commerce'
    | '/api/admin/perks'
    | '/api/admin/prompts'
    | '/api/admin/settlements'
    | '/api/admin/accounts/$userId/role'
    | '/api/admin/beta-invitations/$id/approve'
    | '/api/admin/beta-invitations/$id/reject'
    | '/api/admin/data/$entityKey/import'
    | '/api/admin/releases/$id/publish'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/contact'
    | '/api/health'
    | '/api/releases'
    | '/api/version'
    | '/features/free-to-play'
    | '/api/account/membership'
    | '/api/account/settings'
    | '/api/admin/campaign'
    | '/api/admin/documents'
    | '/api/admin/releases'
    | '/api/atlas/catalog'
    | '/api/auth/$'
    | '/api/beta-invitations/redeem'
    | '/api/beta-invitations/request'
    | '/api/donations/checkout'
    | '/api/player/access'
    | '/api/player/calendar'
    | '/api/player/puzzles'
    | '/api/player/runtime'
    | '/api/store/catalog'
    | '/api/store/checkout'
    | '/api/stripe/webhook'
    | '/api/account/orders/$orderId'
    | '/api/account/sessions/revoke-all-other'
    | '/api/account/sessions/revoke-other'
    | '/api/admin/accounts/$userId'
    | '/api/admin/perks/$perkId'
    | '/api/admin/puzzles/blueprints'
    | '/api/admin/settlements/complete-naming'
    | '/api/admin/settlements/found-city'
    | '/api/admin/settlements/migrate'
    | '/api/account/orders/'
    | '/api/account/sessions/'
    | '/api/admin/accounts/'
    | '/api/admin/assets/'
    | '/api/admin/beta-invitations/'
    | '/api/admin/commerce/'
    | '/api/admin/perks/'
    | '/api/admin/prompts/'
    | '/api/admin/settlements/'
    | '/api/admin/accounts/$userId/role'
    | '/api/admin/beta-invitations/$id/approve'
    | '/api/admin/beta-invitations/$id/reject'
    | '/api/admin/data/$entityKey/import'
    | '/api/admin/releases/$id/publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReleasesRoute: typeof ApiReleasesRoute
  ApiVersionRoute: typeof ApiVersionRoute
  FeaturesFreeToPlayRoute: typeof FeaturesFreeToPlayRoute
  ApiAccountMembershipRoute: typeof ApiAccountMembershipRoute
  ApiAccountSettingsRoute: typeof ApiAccountSettingsRoute
  ApiAdminCampaignRoute: typeof ApiAdminCampaignRoute
  ApiAdminDocumentsRoute: typeof ApiAdminDocumentsRoute
  ApiAdminReleasesRoute: typeof ApiAdminReleasesRouteWithChildren
  ApiAtlasCatalogRoute: typeof ApiAtlasCatalogRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBetaInvitationsRedeemRoute: typeof ApiBetaInvitationsRedeemRoute
  ApiBetaInvitationsRequestRoute: typeof ApiBetaInvitationsRequestRoute
  ApiDonationsCheckoutRoute: typeof ApiDonationsCheckoutRoute
  ApiPlayerAccessRoute: typeof ApiPlayerAccessRoute
  ApiPlayerCalendarRoute: typeof ApiPlayerCalendarRoute
  ApiPlayerPuzzlesRoute: typeof ApiPlayerPuzzlesRoute
  ApiPlayerRuntimeRoute: typeof ApiPlayerRuntimeRoute
  ApiStoreCatalogRoute: typeof ApiStoreCatalogRoute
  ApiStoreCheckoutRoute: typeof ApiStoreCheckoutRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiAccountOrdersOrderIdRoute: typeof ApiAccountOrdersOrderIdRoute
  ApiAccountSessionsRevokeAllOtherRoute: typeof ApiAccountSessionsRevokeAllOtherRoute
  ApiAccountSessionsRevokeOtherRoute: typeof ApiAccountSessionsRevokeOtherRoute
  ApiAdminAccountsUserIdRoute: typeof ApiAdminAccountsUserIdRouteWithChildren
  ApiAdminPerksPerkIdRoute: typeof ApiAdminPerksPerkIdRoute
  ApiAdminPuzzlesBlueprintsRoute: typeof ApiAdminPuzzlesBlueprintsRoute
  ApiAdminSettlementsCompleteNamingRoute: typeof ApiAdminSettlementsCompleteNamingRoute
  ApiAdminSettlementsFoundCityRoute: typeof ApiAdminSettlementsFoundCityRoute
  ApiAdminSettlementsMigrateRoute: typeof ApiAdminSettlementsMigrateRoute
  ApiAccountOrdersIndexRoute: typeof ApiAccountOrdersIndexRoute
  ApiAccountSessionsIndexRoute: typeof ApiAccountSessionsIndexRoute
  ApiAdminAccountsIndexRoute: typeof ApiAdminAccountsIndexRoute
  ApiAdminAssetsIndexRoute: typeof ApiAdminAssetsIndexRoute
  ApiAdminBetaInvitationsIndexRoute: typeof ApiAdminBetaInvitationsIndexRoute
  ApiAdminCommerceIndexRoute: typeof ApiAdminCommerceIndexRoute
  ApiAdminPerksIndexRoute: typeof ApiAdminPerksIndexRoute
  ApiAdminPromptsIndexRoute: typeof ApiAdminPromptsIndexRoute
  ApiAdminSettlementsIndexRoute: typeof ApiAdminSettlementsIndexRoute
  ApiAdminBetaInvitationsIdApproveRoute: typeof ApiAdminBetaInvitationsIdApproveRoute
  ApiAdminBetaInvitationsIdRejectRoute: typeof ApiAdminBetaInvitationsIdRejectRoute
  ApiAdminDataEntityKeyImportRoute: typeof ApiAdminDataEntityKeyImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/releases': {
      id: '/api/releases'
      path: '/api/releases'
      fullPath: '/api/releases'
      preLoaderRoute: typeof ApiReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/free-to-play': {
      id: '/features/free-to-play'
      path: '/features/free-to-play'
      fullPath: '/features/free-to-play'
      preLoaderRoute: typeof FeaturesFreeToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/membership': {
      id: '/api/account/membership'
      path: '/api/account/membership'
      fullPath: '/api/account/membership'
      preLoaderRoute: typeof ApiAccountMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/settings': {
      id: '/api/account/settings'
      path: '/api/account/settings'
      fullPath: '/api/account/settings'
      preLoaderRoute: typeof ApiAccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/campaign': {
      id: '/api/admin/campaign'
      path: '/api/admin/campaign'
      fullPath: '/api/admin/campaign'
      preLoaderRoute: typeof ApiAdminCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/documents': {
      id: '/api/admin/documents'
      path: '/api/admin/documents'
      fullPath: '/api/admin/documents'
      preLoaderRoute: typeof ApiAdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/releases': {
      id: '/api/admin/releases'
      path: '/api/admin/releases'
      fullPath: '/api/admin/releases'
      preLoaderRoute: typeof ApiAdminReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/atlas/catalog': {
      id: '/api/atlas/catalog'
      path: '/api/atlas/catalog'
      fullPath: '/api/atlas/catalog'
      preLoaderRoute: typeof ApiAtlasCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta-invitations/redeem': {
      id: '/api/beta-invitations/redeem'
      path: '/api/beta-invitations/redeem'
      fullPath: '/api/beta-invitations/redeem'
      preLoaderRoute: typeof ApiBetaInvitationsRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta-invitations/request': {
      id: '/api/beta-invitations/request'
      path: '/api/beta-invitations/request'
      fullPath: '/api/beta-invitations/request'
      preLoaderRoute: typeof ApiBetaInvitationsRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donations/checkout': {
      id: '/api/donations/checkout'
      path: '/api/donations/checkout'
      fullPath: '/api/donations/checkout'
      preLoaderRoute: typeof ApiDonationsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/access': {
      id: '/api/player/access'
      path: '/api/player/access'
      fullPath: '/api/player/access'
      preLoaderRoute: typeof ApiPlayerAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/calendar': {
      id: '/api/player/calendar'
      path: '/api/player/calendar'
      fullPath: '/api/player/calendar'
      preLoaderRoute: typeof ApiPlayerCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/puzzles': {
      id: '/api/player/puzzles'
      path: '/api/player/puzzles'
      fullPath: '/api/player/puzzles'
      preLoaderRoute: typeof ApiPlayerPuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/runtime': {
      id: '/api/player/runtime'
      path: '/api/player/runtime'
      fullPath: '/api/player/runtime'
      preLoaderRoute: typeof ApiPlayerRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/catalog': {
      id: '/api/store/catalog'
      path: '/api/store/catalog'
      fullPath: '/api/store/catalog'
      preLoaderRoute: typeof ApiStoreCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store/checkout': {
      id: '/api/store/checkout'
      path: '/api/store/checkout'
      fullPath: '/api/store/checkout'
      preLoaderRoute: typeof ApiStoreCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/orders/': {
      id: '/api/account/orders/'
      path: '/api/account/orders'
      fullPath: '/api/account/orders/'
      preLoaderRoute: typeof ApiAccountOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/orders/$orderId': {
      id: '/api/account/orders/$orderId'
      path: '/api/account/orders/$orderId'
      fullPath: '/api/account/orders/$orderId'
      preLoaderRoute: typeof ApiAccountOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/sessions/': {
      id: '/api/account/sessions/'
      path: '/api/account/sessions'
      fullPath: '/api/account/sessions/'
      preLoaderRoute: typeof ApiAccountSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/sessions/revoke-all-other': {
      id: '/api/account/sessions/revoke-all-other'
      path: '/api/account/sessions/revoke-all-other'
      fullPath: '/api/account/sessions/revoke-all-other'
      preLoaderRoute: typeof ApiAccountSessionsRevokeAllOtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/sessions/revoke-other': {
      id: '/api/account/sessions/revoke-other'
      path: '/api/account/sessions/revoke-other'
      fullPath: '/api/account/sessions/revoke-other'
      preLoaderRoute: typeof ApiAccountSessionsRevokeOtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/accounts/': {
      id: '/api/admin/accounts/'
      path: '/api/admin/accounts'
      fullPath: '/api/admin/accounts/'
      preLoaderRoute: typeof ApiAdminAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/accounts/$userId': {
      id: '/api/admin/accounts/$userId'
      path: '/api/admin/accounts/$userId'
      fullPath: '/api/admin/accounts/$userId'
      preLoaderRoute: typeof ApiAdminAccountsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/assets/': {
      id: '/api/admin/assets/'
      path: '/api/admin/assets'
      fullPath: '/api/admin/assets/'
      preLoaderRoute: typeof ApiAdminAssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/beta-invitations/': {
      id: '/api/admin/beta-invitations/'
      path: '/api/admin/beta-invitations'
      fullPath: '/api/admin/beta-invitations/'
      preLoaderRoute: typeof ApiAdminBetaInvitationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/commerce/': {
      id: '/api/admin/commerce/'
      path: '/api/admin/commerce'
      fullPath: '/api/admin/commerce/'
      preLoaderRoute: typeof ApiAdminCommerceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/perks/': {
      id: '/api/admin/perks/'
      path: '/api/admin/perks'
      fullPath: '/api/admin/perks/'
      preLoaderRoute: typeof ApiAdminPerksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/perks/$perkId': {
      id: '/api/admin/perks/$perkId'
      path: '/api/admin/perks/$perkId'
      fullPath: '/api/admin/perks/$perkId'
      preLoaderRoute: typeof ApiAdminPerksPerkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/prompts/': {
      id: '/api/admin/prompts/'
      path: '/api/admin/prompts'
      fullPath: '/api/admin/prompts/'
      preLoaderRoute: typeof ApiAdminPromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/puzzles/blueprints': {
      id: '/api/admin/puzzles/blueprints'
      path: '/api/admin/puzzles/blueprints'
      fullPath: '/api/admin/puzzles/blueprints'
      preLoaderRoute: typeof ApiAdminPuzzlesBlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settlements/': {
      id: '/api/admin/settlements/'
      path: '/api/admin/settlements'
      fullPath: '/api/admin/settlements/'
      preLoaderRoute: typeof ApiAdminSettlementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settlements/complete-naming': {
      id: '/api/admin/settlements/complete-naming'
      path: '/api/admin/settlements/complete-naming'
      fullPath: '/api/admin/settlements/complete-naming'
      preLoaderRoute: typeof ApiAdminSettlementsCompleteNamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settlements/found-city': {
      id: '/api/admin/settlements/found-city'
      path: '/api/admin/settlements/found-city'
      fullPath: '/api/admin/settlements/found-city'
      preLoaderRoute: typeof ApiAdminSettlementsFoundCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settlements/migrate': {
      id: '/api/admin/settlements/migrate'
      path: '/api/admin/settlements/migrate'
      fullPath: '/api/admin/settlements/migrate'
      preLoaderRoute: typeof ApiAdminSettlementsMigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/accounts/$userId/role': {
      id: '/api/admin/accounts/$userId/role'
      path: '/role'
      fullPath: '/api/admin/accounts/$userId/role'
      preLoaderRoute: typeof ApiAdminAccountsUserIdRoleRouteImport
      parentRoute: typeof ApiAdminAccountsUserIdRoute
    }
    '/api/admin/beta-invitations/$id/approve': {
      id: '/api/admin/beta-invitations/$id/approve'
      path: '/api/admin/beta-invitations/$id/approve'
      fullPath: '/api/admin/beta-invitations/$id/approve'
      preLoaderRoute: typeof ApiAdminBetaInvitationsIdApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/beta-invitations/$id/reject': {
      id: '/api/admin/beta-invitations/$id/reject'
      path: '/api/admin/beta-invitations/$id/reject'
      fullPath: '/api/admin/beta-invitations/$id/reject'
      preLoaderRoute: typeof ApiAdminBetaInvitationsIdRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/data/$entityKey/import': {
      id: '/api/admin/data/$entityKey/import'
      path: '/api/admin/data/$entityKey/import'
      fullPath: '/api/admin/data/$entityKey/import'
      preLoaderRoute: typeof ApiAdminDataEntityKeyImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/releases/$id/publish': {
      id: '/api/admin/releases/$id/publish'
      path: '/$id/publish'
      fullPath: '/api/admin/releases/$id/publish'
      preLoaderRoute: typeof ApiAdminReleasesIdPublishRouteImport
      parentRoute: typeof ApiAdminReleasesRoute
    }
  }
}

interface ApiAdminReleasesRouteChildren {
  ApiAdminReleasesIdPublishRoute: typeof ApiAdminReleasesIdPublishRoute
}

const ApiAdminReleasesRouteChildren: ApiAdminReleasesRouteChildren = {
  ApiAdminReleasesIdPublishRoute: ApiAdminReleasesIdPublishRoute,
}

const ApiAdminReleasesRouteWithChildren =
  ApiAdminReleasesRoute._addFileChildren(ApiAdminReleasesRouteChildren)

interface ApiAdminAccountsUserIdRouteChildren {
  ApiAdminAccountsUserIdRoleRoute: typeof ApiAdminAccountsUserIdRoleRoute
}

const ApiAdminAccountsUserIdRouteChildren: ApiAdminAccountsUserIdRouteChildren =
  {
    ApiAdminAccountsUserIdRoleRoute: ApiAdminAccountsUserIdRoleRoute,
  }

const ApiAdminAccountsUserIdRouteWithChildren =
  ApiAdminAccountsUserIdRoute._addFileChildren(
    ApiAdminAccountsUserIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiContactRoute: ApiContactRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReleasesRoute: ApiReleasesRoute,
  ApiVersionRoute: ApiVersionRoute,
  FeaturesFreeToPlayRoute: FeaturesFreeToPlayRoute,
  ApiAccountMembershipRoute: ApiAccountMembershipRoute,
  ApiAccountSettingsRoute: ApiAccountSettingsRoute,
  ApiAdminCampaignRoute: ApiAdminCampaignRoute,
  ApiAdminDocumentsRoute: ApiAdminDocumentsRoute,
  ApiAdminReleasesRoute: ApiAdminReleasesRouteWithChildren,
  ApiAtlasCatalogRoute: ApiAtlasCatalogRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBetaInvitationsRedeemRoute: ApiBetaInvitationsRedeemRoute,
  ApiBetaInvitationsRequestRoute: ApiBetaInvitationsRequestRoute,
  ApiDonationsCheckoutRoute: ApiDonationsCheckoutRoute,
  ApiPlayerAccessRoute: ApiPlayerAccessRoute,
  ApiPlayerCalendarRoute: ApiPlayerCalendarRoute,
  ApiPlayerPuzzlesRoute: ApiPlayerPuzzlesRoute,
  ApiPlayerRuntimeRoute: ApiPlayerRuntimeRoute,
  ApiStoreCatalogRoute: ApiStoreCatalogRoute,
  ApiStoreCheckoutRoute: ApiStoreCheckoutRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiAccountOrdersOrderIdRoute: ApiAccountOrdersOrderIdRoute,
  ApiAccountSessionsRevokeAllOtherRoute: ApiAccountSessionsRevokeAllOtherRoute,
  ApiAccountSessionsRevokeOtherRoute: ApiAccountSessionsRevokeOtherRoute,
  ApiAdminAccountsUserIdRoute: ApiAdminAccountsUserIdRouteWithChildren,
  ApiAdminPerksPerkIdRoute: ApiAdminPerksPerkIdRoute,
  ApiAdminPuzzlesBlueprintsRoute: ApiAdminPuzzlesBlueprintsRoute,
  ApiAdminSettlementsCompleteNamingRoute:
    ApiAdminSettlementsCompleteNamingRoute,
  ApiAdminSettlementsFoundCityRoute: ApiAdminSettlementsFoundCityRoute,
  ApiAdminSettlementsMigrateRoute: ApiAdminSettlementsMigrateRoute,
  ApiAccountOrdersIndexRoute: ApiAccountOrdersIndexRoute,
  ApiAccountSessionsIndexRoute: ApiAccountSessionsIndexRoute,
  ApiAdminAccountsIndexRoute: ApiAdminAccountsIndexRoute,
  ApiAdminAssetsIndexRoute: ApiAdminAssetsIndexRoute,
  ApiAdminBetaInvitationsIndexRoute: ApiAdminBetaInvitationsIndexRoute,
  ApiAdminCommerceIndexRoute: ApiAdminCommerceIndexRoute,
  ApiAdminPerksIndexRoute: ApiAdminPerksIndexRoute,
  ApiAdminPromptsIndexRoute: ApiAdminPromptsIndexRoute,
  ApiAdminSettlementsIndexRoute: ApiAdminSettlementsIndexRoute,
  ApiAdminBetaInvitationsIdApproveRoute: ApiAdminBetaInvitationsIdApproveRoute,
  ApiAdminBetaInvitationsIdRejectRoute: ApiAdminBetaInvitationsIdRejectRoute,
  ApiAdminDataEntityKeyImportRoute: ApiAdminDataEntityKeyImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
