/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as FeaturesFreeToPlayRouteImport } from './routes/features.free-to-play'
import { Route as ApiAtlasCatalogRouteImport } from './routes/api/atlas/catalog'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBetaInvitationsRedeemRouteImport } from './routes/api/beta-invitations/redeem'
import { Route as ApiBetaInvitationsRequestRouteImport } from './routes/api/beta-invitations/request'
import { Route as ApiPlayerAccessRouteImport } from './routes/api/player/access'
import { Route as ApiAccountSessionsRevokeAllOtherRouteImport } from './routes/api/account/sessions/revoke-all-other'
import { Route as ApiAccountSessionsRevokeOtherRouteImport } from './routes/api/account/sessions/revoke-other'
import { Route as ApiAdminAccountsIndexRouteImport } from './routes/api/admin/accounts/index'
import { Route as ApiAdminAccountsUserIdRouteImport } from './routes/api/admin/accounts/$userId'
import { Route as ApiAdminBetaInvitationsIndexRouteImport } from './routes/api/admin/beta-invitations/index'
import { Route as ApiAdminAccountsUserIdRoleRouteImport } from './routes/api/admin/accounts/$userId/role'
import { Route as ApiAdminBetaInvitationsIdApproveRouteImport } from './routes/api/admin/beta-invitations/$id/approve'
import { Route as ApiAdminBetaInvitationsIdRejectRouteImport } from './routes/api/admin/beta-invitations/$id/reject'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesFreeToPlayRoute = FeaturesFreeToPlayRouteImport.update({
  id: '/features/free-to-play',
  path: '/features/free-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAtlasCatalogRoute = ApiAtlasCatalogRouteImport.update({
  id: '/api/atlas/catalog',
  path: '/api/atlas/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetaInvitationsRedeemRoute =
  ApiBetaInvitationsRedeemRouteImport.update({
    id: '/api/beta-invitations/redeem',
    path: '/api/beta-invitations/redeem',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBetaInvitationsRequestRoute =
  ApiBetaInvitationsRequestRouteImport.update({
    id: '/api/beta-invitations/request',
    path: '/api/beta-invitations/request',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPlayerAccessRoute = ApiPlayerAccessRouteImport.update({
  id: '/api/player/access',
  path: '/api/player/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountSessionsRevokeAllOtherRoute =
  ApiAccountSessionsRevokeAllOtherRouteImport.update({
    id: '/api/account/sessions/revoke-all-other',
    path: '/api/account/sessions/revoke-all-other',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountSessionsRevokeOtherRoute =
  ApiAccountSessionsRevokeOtherRouteImport.update({
    id: '/api/account/sessions/revoke-other',
    path: '/api/account/sessions/revoke-other',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAccountsIndexRoute = ApiAdminAccountsIndexRouteImport.update({
  id: '/api/admin/accounts/',
  path: '/api/admin/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAccountsUserIdRoute = ApiAdminAccountsUserIdRouteImport.update({
  id: '/api/admin/accounts/$userId',
  path: '/api/admin/accounts/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBetaInvitationsIndexRoute =
  ApiAdminBetaInvitationsIndexRouteImport.update({
    id: '/api/admin/beta-invitations/',
    path: '/api/admin/beta-invitations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminAccountsUserIdRoleRoute =
  ApiAdminAccountsUserIdRoleRouteImport.update({
    id: '/role',
    path: '/role',
    getParentRoute: () => ApiAdminAccountsUserIdRoute,
  } as any)
const ApiAdminBetaInvitationsIdApproveRoute =
  ApiAdminBetaInvitationsIdApproveRouteImport.update({
    id: '/api/admin/beta-invitations/$id/approve',
    path: '/api/admin/beta-invitations/$id/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminBetaInvitationsIdRejectRoute =
  ApiAdminBetaInvitationsIdRejectRouteImport.update({
    id: '/api/admin/beta-invitations/$id/reject',
    path: '/api/admin/beta-invitations/$id/reject',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/features/free-to-play': typeof FeaturesFreeToPlayRoute
  '/api/atlas/catalog': typeof ApiAtlasCatalogRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta-invitations/redeem': typeof ApiBetaInvitationsRedeemRoute
  '/api/beta-invitations/request': typeof ApiBetaInvitationsRequestRoute
  '/api/player/access': typeof ApiPlayerAccessRoute
  '/api/account/sessions/revoke-all-other': typeof ApiAccountSessionsRevokeAllOtherRoute
  '/api/account/sessions/revoke-other': typeof ApiAccountSessionsRevokeOtherRoute
  '/api/admin/accounts/$userId': typeof ApiAdminAccountsUserIdRouteWithChildren
  '/api/admin/accounts/': typeof ApiAdminAccountsIndexRoute
  '/api/admin/beta-invitations/': typeof ApiAdminBetaInvitationsIndexRoute
  '/api/admin/accounts/$userId/role': typeof ApiAdminAccountsUserIdRoleRoute
  '/api/admin/beta-invitations/$id/approve': typeof ApiAdminBetaInvitationsIdApproveRoute
  '/api/admin/beta-invitations/$id/reject': typeof ApiAdminBetaInvitationsIdRejectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/features/free-to-play': typeof FeaturesFreeToPlayRoute
  '/api/atlas/catalog': typeof ApiAtlasCatalogRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta-invitations/redeem': typeof ApiBetaInvitationsRedeemRoute
  '/api/beta-invitations/request': typeof ApiBetaInvitationsRequestRoute
  '/api/player/access': typeof ApiPlayerAccessRoute
  '/api/account/sessions/revoke-all-other': typeof ApiAccountSessionsRevokeAllOtherRoute
  '/api/account/sessions/revoke-other': typeof ApiAccountSessionsRevokeOtherRoute
  '/api/admin/accounts/$userId': typeof ApiAdminAccountsUserIdRouteWithChildren
  '/api/admin/accounts': typeof ApiAdminAccountsIndexRoute
  '/api/admin/beta-invitations': typeof ApiAdminBetaInvitationsIndexRoute
  '/api/admin/accounts/$userId/role': typeof ApiAdminAccountsUserIdRoleRoute
  '/api/admin/beta-invitations/$id/approve': typeof ApiAdminBetaInvitationsIdApproveRoute
  '/api/admin/beta-invitations/$id/reject': typeof ApiAdminBetaInvitationsIdRejectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/features/free-to-play': typeof FeaturesFreeToPlayRoute
  '/api/atlas/catalog': typeof ApiAtlasCatalogRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/beta-invitations/redeem': typeof ApiBetaInvitationsRedeemRoute
  '/api/beta-invitations/request': typeof ApiBetaInvitationsRequestRoute
  '/api/player/access': typeof ApiPlayerAccessRoute
  '/api/account/sessions/revoke-all-other': typeof ApiAccountSessionsRevokeAllOtherRoute
  '/api/account/sessions/revoke-other': typeof ApiAccountSessionsRevokeOtherRoute
  '/api/admin/accounts/$userId': typeof ApiAdminAccountsUserIdRouteWithChildren
  '/api/admin/accounts/': typeof ApiAdminAccountsIndexRoute
  '/api/admin/beta-invitations/': typeof ApiAdminBetaInvitationsIndexRoute
  '/api/admin/accounts/$userId/role': typeof ApiAdminAccountsUserIdRoleRoute
  '/api/admin/beta-invitations/$id/approve': typeof ApiAdminBetaInvitationsIdApproveRoute
  '/api/admin/beta-invitations/$id/reject': typeof ApiAdminBetaInvitationsIdRejectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/features/free-to-play'
    | '/api/atlas/catalog'
    | '/api/auth/$'
    | '/api/beta-invitations/redeem'
    | '/api/beta-invitations/request'
    | '/api/player/access'
    | '/api/account/sessions/revoke-all-other'
    | '/api/account/sessions/revoke-other'
    | '/api/admin/accounts/$userId'
    | '/api/admin/accounts/'
    | '/api/admin/beta-invitations/'
    | '/api/admin/accounts/$userId/role'
    | '/api/admin/beta-invitations/$id/approve'
    | '/api/admin/beta-invitations/$id/reject'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/features/free-to-play'
    | '/api/atlas/catalog'
    | '/api/auth/$'
    | '/api/beta-invitations/redeem'
    | '/api/beta-invitations/request'
    | '/api/player/access'
    | '/api/account/sessions/revoke-all-other'
    | '/api/account/sessions/revoke-other'
    | '/api/admin/accounts/$userId'
    | '/api/admin/accounts'
    | '/api/admin/beta-invitations'
    | '/api/admin/accounts/$userId/role'
    | '/api/admin/beta-invitations/$id/approve'
    | '/api/admin/beta-invitations/$id/reject'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/features/free-to-play'
    | '/api/atlas/catalog'
    | '/api/auth/$'
    | '/api/beta-invitations/redeem'
    | '/api/beta-invitations/request'
    | '/api/player/access'
    | '/api/account/sessions/revoke-all-other'
    | '/api/account/sessions/revoke-other'
    | '/api/admin/accounts/$userId'
    | '/api/admin/accounts/'
    | '/api/admin/beta-invitations/'
    | '/api/admin/accounts/$userId/role'
    | '/api/admin/beta-invitations/$id/approve'
    | '/api/admin/beta-invitations/$id/reject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  FeaturesFreeToPlayRoute: typeof FeaturesFreeToPlayRoute
  ApiAtlasCatalogRoute: typeof ApiAtlasCatalogRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBetaInvitationsRedeemRoute: typeof ApiBetaInvitationsRedeemRoute
  ApiBetaInvitationsRequestRoute: typeof ApiBetaInvitationsRequestRoute
  ApiPlayerAccessRoute: typeof ApiPlayerAccessRoute
  ApiAccountSessionsRevokeAllOtherRoute: typeof ApiAccountSessionsRevokeAllOtherRoute
  ApiAccountSessionsRevokeOtherRoute: typeof ApiAccountSessionsRevokeOtherRoute
  ApiAdminAccountsUserIdRoute: typeof ApiAdminAccountsUserIdRouteWithChildren
  ApiAdminAccountsIndexRoute: typeof ApiAdminAccountsIndexRoute
  ApiAdminBetaInvitationsIndexRoute: typeof ApiAdminBetaInvitationsIndexRoute
  ApiAdminBetaInvitationsIdApproveRoute: typeof ApiAdminBetaInvitationsIdApproveRoute
  ApiAdminBetaInvitationsIdRejectRoute: typeof ApiAdminBetaInvitationsIdRejectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/free-to-play': {
      id: '/features/free-to-play'
      path: '/features/free-to-play'
      fullPath: '/features/free-to-play'
      preLoaderRoute: typeof FeaturesFreeToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/atlas/catalog': {
      id: '/api/atlas/catalog'
      path: '/api/atlas/catalog'
      fullPath: '/api/atlas/catalog'
      preLoaderRoute: typeof ApiAtlasCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta-invitations/redeem': {
      id: '/api/beta-invitations/redeem'
      path: '/api/beta-invitations/redeem'
      fullPath: '/api/beta-invitations/redeem'
      preLoaderRoute: typeof ApiBetaInvitationsRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beta-invitations/request': {
      id: '/api/beta-invitations/request'
      path: '/api/beta-invitations/request'
      fullPath: '/api/beta-invitations/request'
      preLoaderRoute: typeof ApiBetaInvitationsRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player/access': {
      id: '/api/player/access'
      path: '/api/player/access'
      fullPath: '/api/player/access'
      preLoaderRoute: typeof ApiPlayerAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/sessions/revoke-all-other': {
      id: '/api/account/sessions/revoke-all-other'
      path: '/api/account/sessions/revoke-all-other'
      fullPath: '/api/account/sessions/revoke-all-other'
      preLoaderRoute: typeof ApiAccountSessionsRevokeAllOtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/sessions/revoke-other': {
      id: '/api/account/sessions/revoke-other'
      path: '/api/account/sessions/revoke-other'
      fullPath: '/api/account/sessions/revoke-other'
      preLoaderRoute: typeof ApiAccountSessionsRevokeOtherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/accounts/': {
      id: '/api/admin/accounts/'
      path: '/api/admin/accounts'
      fullPath: '/api/admin/accounts/'
      preLoaderRoute: typeof ApiAdminAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/accounts/$userId': {
      id: '/api/admin/accounts/$userId'
      path: '/api/admin/accounts/$userId'
      fullPath: '/api/admin/accounts/$userId'
      preLoaderRoute: typeof ApiAdminAccountsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/beta-invitations/': {
      id: '/api/admin/beta-invitations/'
      path: '/api/admin/beta-invitations'
      fullPath: '/api/admin/beta-invitations/'
      preLoaderRoute: typeof ApiAdminBetaInvitationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/accounts/$userId/role': {
      id: '/api/admin/accounts/$userId/role'
      path: '/role'
      fullPath: '/api/admin/accounts/$userId/role'
      preLoaderRoute: typeof ApiAdminAccountsUserIdRoleRouteImport
      parentRoute: typeof ApiAdminAccountsUserIdRoute
    }
    '/api/admin/beta-invitations/$id/approve': {
      id: '/api/admin/beta-invitations/$id/approve'
      path: '/api/admin/beta-invitations/$id/approve'
      fullPath: '/api/admin/beta-invitations/$id/approve'
      preLoaderRoute: typeof ApiAdminBetaInvitationsIdApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/beta-invitations/$id/reject': {
      id: '/api/admin/beta-invitations/$id/reject'
      path: '/api/admin/beta-invitations/$id/reject'
      fullPath: '/api/admin/beta-invitations/$id/reject'
      preLoaderRoute: typeof ApiAdminBetaInvitationsIdRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAdminAccountsUserIdRouteChildren {
  ApiAdminAccountsUserIdRoleRoute: typeof ApiAdminAccountsUserIdRoleRoute
}

const ApiAdminAccountsUserIdRouteChildren: ApiAdminAccountsUserIdRouteChildren =
  {
    ApiAdminAccountsUserIdRoleRoute: ApiAdminAccountsUserIdRoleRoute,
  }

const ApiAdminAccountsUserIdRouteWithChildren =
  ApiAdminAccountsUserIdRoute._addFileChildren(
    ApiAdminAccountsUserIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  FeaturesFreeToPlayRoute: FeaturesFreeToPlayRoute,
  ApiAtlasCatalogRoute: ApiAtlasCatalogRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBetaInvitationsRedeemRoute: ApiBetaInvitationsRedeemRoute,
  ApiBetaInvitationsRequestRoute: ApiBetaInvitationsRequestRoute,
  ApiPlayerAccessRoute: ApiPlayerAccessRoute,
  ApiAccountSessionsRevokeAllOtherRoute: ApiAccountSessionsRevokeAllOtherRoute,
  ApiAccountSessionsRevokeOtherRoute: ApiAccountSessionsRevokeOtherRoute,
  ApiAdminAccountsUserIdRoute: ApiAdminAccountsUserIdRouteWithChildren,
  ApiAdminAccountsIndexRoute: ApiAdminAccountsIndexRoute,
  ApiAdminBetaInvitationsIndexRoute: ApiAdminBetaInvitationsIndexRoute,
  ApiAdminBetaInvitationsIdApproveRoute: ApiAdminBetaInvitationsIdApproveRoute,
  ApiAdminBetaInvitationsIdRejectRoute: ApiAdminBetaInvitationsIdRejectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
