%% Found City
flowchart LR
  Owningworldcontext0["Owning world context"]
  ChooseSite1["Choose Site"]
  Chooseoriginpopula2["Choose origin populations"]
  Validatedepartures3["Validate departures"]
  Ceil90percentarriv4["Ceil 90 percent arrival"]
  ApportionbyBreed5["Apportion by Breed"]
  Namewithnearbyempt6["Name with nearby empty"]
  Atomiccreateandeve7["Atomic create and events"]
  Owningworldcontext0 --> ChooseSite1
  ChooseSite1 --> Chooseoriginpopula2
  Chooseoriginpopula2 --> Validatedepartures3
  Validatedepartures3 --> Ceil90percentarriv4
  Ceil90percentarriv4 --> ApportionbyBreed5
  ApportionbyBreed5 --> Namewithnearbyempt6
  Namewithnearbyempt6 --> Atomiccreateandeve7
