import { createFileRoute } from "@tanstack/react-router";
import { z } from "zod";

import { requireAdministration } from "../../../server/access";
import { getDatabase } from "../../../server/database";

const ability = z.enum(["CHARISMA", "DEXTERITY", "INTELLIGENCE", "STAMINA", "STRENGTH", "WISDOM"]);
const knowledgeSkill = z.enum(["EIDETIC_MEMORY", "PHOTOGRAPHIC_MEMORY", "RECOGNITION", "ORIENTATION", "RESEARCH", "ORIGINS", "LORE", "GOSSIP", "PERFECT_PITCH", "CONNECTIONS", "TRACE"]);
const awarenessSkill = z.enum(["DANGER_SENSE", "TRAP_SENSE", "POISON_SENSE", "DIPLOMACY", "DECEPTION_SENSE", "READ_BETWEEN_THE_LINES", "EMPATHY", "STREETWISE", "GUARDIAN", "FIRST_AID", "RESOLVE"]);
const heirloom = z.enum(["NECKLACE", "BRACELET", "EARRINGS", "CLOAK_CLASP", "LIGHTER", "POCKETWATCH", "COIN_HEAD_BLACKENED", "COIN_TAIL_BLACKENED", "RING", "TATTOO", "BIRTHMARK", "BROOCH", "HAIR_BARRETTE", "BELT_BUCKLE", "BACKPACK_CLASP"]);
const assignmentSchema = z.object({ action: z.literal("assignment"), companionKey: z.enum(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"]), worldKey: z.enum(["CONCORD", "RUIN", "SCHISM"]), gender: z.string().trim().min(1).max(100), age: z.number().int().nonnegative(), occupationId: z.string().min(1), faction: z.enum(["CONCORD", "RUIN", "SCHISM"]), knowledgeSkill: knowledgeSkill.nullable(), awarenessSkill: awarenessSkill.nullable(), primaryAttribute: ability, secondaryAttribute: ability, worldHeirloom: heirloom }).strict();
const bindingSchema = z.object({ action: z.literal("transformation"), companionKey: z.enum(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"]), layetteId: z.string().min(1) }).strict();
const inputSchema = z.discriminatedUnion("action", [assignmentSchema, bindingSchema]);

export const Route = createFileRoute("/api/admin/companion-planner")({ server: { handlers: {
  GET: async ({ request }) => { try { await requireAdministration(request); const database = getDatabase(); const [companions, occupations, layettes] = await Promise.all([database.companion.findMany({ orderBy: { companionKey: "asc" }, include: { soul: true, transformationBinding: true, concordProtagonist: { include: { character: true } }, ruinProtagonist: { include: { character: true } }, schismProtagonist: { include: { character: true } } } }), database.occupation.findMany({ include: { affinities: { orderBy: { ordinal: "asc" } } }, orderBy: { name: "asc" } }), database.layette.findMany({ orderBy: { name: "asc" } })]); return Response.json({ companions, occupations, layettes }); } catch (error) { if (error instanceof Response) return error; throw error; } },
  PUT: async ({ request }) => { try { await requireAdministration(request); const input = inputSchema.parse(await request.json()); const database = getDatabase(); if (input.action === "transformation") { const capability = await database.capabilityDefinition.findUniqueOrThrow({ where: { code: "COMPANION_TRANSFORMATION_COMPLETE" } }); return Response.json({ binding: await database.companionTransformationBinding.upsert({ where: { companionKey: input.companionKey }, create: { companionKey: input.companionKey, layetteId: input.layetteId, capabilityDefinitionId: capability.capabilityDefinitionId }, update: { layetteId: input.layetteId, capabilityDefinitionId: capability.capabilityDefinitionId } }) }); } const companion = await database.companion.findUniqueOrThrow({ where: { companionKey: input.companionKey } }); const occupation = await database.occupation.findUniqueOrThrow({ where: { occupationId: input.occupationId }, include: { affinities: true } }); const allowed = new Set(occupation.affinities.map((affinity) => affinity.abilityType)); if (!allowed.has(input.primaryAttribute) || !allowed.has(input.secondaryAttribute)) return Response.json({ error: "Both attributes must be present in the selected Occupation affinity." }, { status: 409 }); const protagonistId = input.worldKey === "CONCORD" ? companion.concordProtagonistId : input.worldKey === "RUIN" ? companion.ruinProtagonistId : companion.schismProtagonistId; return Response.json({ assignment: await database.protagonist.update({ where: { protagonistId }, data: { gender: input.gender, age: input.age, occupationId: input.occupationId, faction: input.faction, knowledgeSkill: input.knowledgeSkill, awarenessSkill: input.awarenessSkill, primaryAttribute: input.primaryAttribute, secondaryAttribute: input.secondaryAttribute, worldHeirloom: input.worldHeirloom } }) }); } catch (error) { if (error instanceof Response) return error; if (error instanceof z.ZodError || error instanceof SyntaxError) return Response.json({ error: "Companion planner input is invalid." }, { status: 400 }); return Response.json({ error: "Companion planner change could not be saved." }, { status: 409 }); } },
} } });
