import { createFileRoute } from "@tanstack/react-router";
import { z } from "zod";

import { AbilityType, AwarenessSkill, CompanionKey, Faction, Heirloom, KnowledgeSkill, WorldKey } from "../../../generated/prisma/enums";
import { requireAdministration } from "../../../server/access";
import { getDatabase } from "../../../server/database";

const assignmentSchema = z.object({ action: z.literal("assignment"), companionKey: z.enum(CompanionKey), worldKey: z.enum(WorldKey), gender: z.string().trim().min(1).max(100), age: z.number().int().nonnegative(), occupationId: z.string().min(1), faction: z.enum(Faction), primaryAttribute: z.enum(AbilityType), secondaryAttribute: z.enum(AbilityType) }).strict();
const definitionSchema = z.object({ action: z.literal("definition"), companionKey: z.enum(CompanionKey), heirloom: z.enum(Heirloom), knowledgeSkill: z.enum(KnowledgeSkill), awarenessSkill: z.enum(AwarenessSkill) }).strict();
const bindingSchema = z.object({ action: z.literal("transformation"), companionKey: z.enum(CompanionKey), layetteId: z.string().min(1) }).strict();
const inputSchema = z.discriminatedUnion("action", [assignmentSchema, definitionSchema, bindingSchema]);

export const Route = createFileRoute("/api/admin/companion-planner")({ server: { handlers: {
  GET: async ({ request }) => { try { await requireAdministration(request); const database = getDatabase(); const [companions, occupations, layettes] = await Promise.all([database.companionDef.findMany({ orderBy: { companionKey: "asc" }, include: { soul: true, transformationBinding: true, concordCharacter: true, ruinCharacter: true, schismCharacter: true, companions: { include: { character: true } } } }), database.occupation.findMany({ include: { affinities: { orderBy: { ordinal: "asc" } } }, orderBy: { name: "asc" } }), database.layette.findMany({ orderBy: { name: "asc" } })]); return Response.json({ companions, occupations, layettes }); } catch (error) { if (error instanceof Response) return error; throw error; } },
  PUT: async ({ request }) => { try { await requireAdministration(request); const input = inputSchema.parse(await request.json()); const database = getDatabase(); if (input.action === "transformation") { const capability = await database.capabilityDefinition.findUniqueOrThrow({ where: { code: "COMPANION_TRANSFORMATION_COMPLETE" } }); return Response.json({ binding: await database.companionTransformationBinding.upsert({ where: { companionKey: input.companionKey }, create: { companionKey: input.companionKey, layetteId: input.layetteId, capabilityDefinitionId: capability.capabilityDefinitionId }, update: { layetteId: input.layetteId, capabilityDefinitionId: capability.capabilityDefinitionId } }) }); } if (input.action === "definition") return Response.json({ definition: await database.companionDef.update({ where: { companionKey: input.companionKey }, data: { heirloom: input.heirloom, knowledgeSkill: input.knowledgeSkill, awarenessSkill: input.awarenessSkill } }) }); const definition = await database.companionDef.findUniqueOrThrow({ where: { companionKey: input.companionKey } }); const characterId = input.worldKey === "CONCORD" ? definition.concordCharacterId : input.worldKey === "RUIN" ? definition.ruinCharacterId : definition.schismCharacterId; const occupation = await database.occupation.findUniqueOrThrow({ where: { occupationId: input.occupationId }, include: { affinities: true } }); const allowed = new Set(occupation.affinities.map((affinity) => affinity.abilityType)); if (!allowed.has(input.primaryAttribute) || !allowed.has(input.secondaryAttribute)) return Response.json({ error: "Both attributes must be present in the selected Occupation affinity." }, { status: 409 }); return Response.json({ assignment: await database.character.update({ where: { characterId }, data: { gender: input.gender, age: input.age, occupationId: input.occupationId, faction: input.faction, primaryAttribute: input.primaryAttribute, secondaryAttribute: input.secondaryAttribute, worldKey: input.worldKey, soulId: definition.soulId } }) }); } catch (error) { if (error instanceof Response) return error; if (error instanceof z.ZodError || error instanceof SyntaxError) return Response.json({ error: "Companion planner input is invalid." }, { status: 400 }); return Response.json({ error: "Companion planner change could not be saved." }, { status: 409 }); } },
} } });
